---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: littlelink
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/techno-tim/littlelink-server
      tag: latest@sha256:6302fcfb0a257c5ca83bd9bbc0699041d8145fbfe9c6c6c76f7cadb9fe13b571
      pullPolicy: Always
    env:
      TZ: Europe/Stockholm
      META_TITLE: Anton Josefsson
      META_DESCRIPTION: Anton Josefsson - Links
      META_AUTHOR: Anton Josefsson <antonjosefsson@hotmail.se>
      THEME: Dark
      FAVICON_URL: https://avatars.githubusercontent.com/u/18258738?v=4
      AVATAR_URL: https://avatars.githubusercontent.com/u/18258738?v=4
      AVATAR_2X_URL: https://avatars.githubusercontent.com/u/18258738?v=4
      AVATAR_ALT: Anton Josefsson <antonjosefsson@hotmail.se>
      NAME: Anton Josefsson
      BIO: 🤘 Jammin' with the 💻 console 🤠 cowboys in 🌐 cyberspace
      CUSTOM_BUTTON_TEXT: K8s Cluster
      CUSTOM_BUTTON_URL: https://github.com/s0undy/kube-ops
      CUSTOM_BUTTON_COLOR: #000000
      CUSTOM_BUTTON_TEXT_COLOR: #ffffff
      CUSTOM_BUTTON_ALT_TEXT: My GitOps managed Kubernetes cluster
      CUSTOM_BUTTON_NAME: K8s Cluster
      CUSTOM_BUTTON_ICON: fas fa-cog
      GITHUB: https://github.com/s0undy
      LINKED_IN: https://www.linkedin.com/in/anton-josefsson-925103133/
      INSTAGRAM: https://www.instagram.com/antonjoosefssoon/
      EMAIL: anton.josefsson@josefssonit.se
      FOOTER: Anton Josefsson @ 2022
      
    service:
      main:
        ports:
          http:
            enabled: true
            port: 80
            targetPort: 3000
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: "television-box"
          hajimari.io/appName: "Littlelink"
          hajimari.io/group: "Other"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns.home.arpa/enabled: "true"
        hosts:
          - host: &host "links.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    resources:
      requests:
        memory: 64M
      limits:
        memory: 100M
