---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: littlelink
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/techno-tim/littlelink-server
      tag: latest@sha256:6302fcfb0a257c5ca83bd9bbc0699041d8145fbfe9c6c6c76f7cadb9fe13b571
      pullPolicy: Always
    env:
      TZ: Europe/Stockholm
      META_TITLE: Anton Josefsson - Links Page
      META_DESCRIPTION: Anton Josefsson - Links Page
      META_AUTHOR: Anton Josefsson <antonjosefsson@hotmail.se>
      THEME: Dark
      FAVICON_URL: https://avatars.githubusercontent.com/u/18258738?v=4
      AVATAR_URL: https://avatars.githubusercontent.com/u/18258738?v=4
      AVATAR_2X_URL: https://avatars.githubusercontent.com/u/18258738?v=4
      AVATAR_ALT: Anton Josefsson <antonjosefsson@hotmail.se>
      NAME: Anton Josefsson
      BIO: 🤘 Jammin' with the 💻 console 🤠 cowboys in 🌐 cyberspace
      GITHUB: https://github.com/s0undy
      # TWITTER: https://sprk.sh/twitter
      # INSTAGRAM: https://www.instagram.com/techno.tim
      #YOUTUBE: https://sprk.sh/youtube
      # TWITCH: https://www.twitch.tv/technotim/
      # DISCORD: https://discord.gg/DJKexrJ
      # TIKTOK: https://www.tiktok.com/@technotim
      # KIT: https://kit.co/TechnoTim
      # FACEBOOK: https://facebook.com
      # FACEBOOK_MESSENGER: https://facebook.com
      LINKED_IN: https://www.linkedin.com/in/anton-josefsson-925103133/
      # PRODUCT_HUNT: https://www.producthunt.com/
      # SNAPCHAT: https://www.snapchat.com/
      # SPOTIFY: https://www.spotify.com/
      # REDDIT: https://www.reddit.com/
      # MEDIUM: https://medium.com
      # PINTEREST: https://www.pinterest.com/
      EMAIL: antonjosefsson@hotmail.se
      # EMAIL_ALT: you@example.com
      #SOUND_CLOUD: https://sprk.sh/music
      # FIGMA: https://figma.com
      # TELEGRAM: https://telegram.org/
      # TUMBLR: https://www.tumblr.com/
      # STEAM: https://steamcommunity.com/
      # VIMEO: https://vimeo.com/
      # WORDPRESS: https://wordpress.com/
      # GOODREADS: https://www.goodreads.com/
      # SKOOB: https://www.skoob.com.br/
      FOOTER: Ses på LAN!
    service:
      main:
        ports:
          http:
            enabled: true
            port: 80
            targetPort: 3000
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: "television-box"
          hajimari.io/appName: "Littlelink"
          hajimari.io/group: "Other"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns.home.arpa/enabled: "true"
        hosts:
          - host: &host "links.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    resources:
      requests:
        memory: 64M
      limits:
        memory: 100M
