apiVersion: v1
kind: Secret
metadata:
    name: pve-exporter-secret
stringData:
    PVE_USER: ENC[AES256_GCM,data:Q8S7mcA0/QA5Odl6XeU=,iv:YUPWqGLeWJ3LWpjNevRTqFRkPLxCLSBTZd6iLhD7zhY=,tag:AfKIfzdR3nWKdps3adrEcQ==,type:str]
    PVE_TOKEN_NAME: ENC[AES256_GCM,data:TXTu8JTls0QAiA==,iv:uYC0HoDrbO0wa6lQjFgFLRNx9Z1XtulHjCvWEWKaFOc=,tag:2N3ClDpyfEuZ0/JUkQ9xvQ==,type:str]
    PVE_TOKEN_VALUE: ENC[AES256_GCM,data:G1DQBqBBb8g8GRsv2P4zU1LcMHI6Pjl7PE2TB8+h3cSBb87L,iv:TyIDlFnlKCh6VI1ikSwxQrg1ApyOZSskEcV0TtbeR1w=,tag:oiOf0d1U+w8NFGfqszb53Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1d0d0ME5YMGJJRUFrZzlM
            cEhaR2RGb2hHb1I1ZkxaUlI0OHBYcFViR1Q4ClhmTWR0a3RzTzFGTUVwa0p1YWdN
            Y2tHUm9SREwxTC84aFBDY2ZOZzVFbzAKLS0tIHVJRWZSd29FQm0veXQwcWZROG52
            dlA0TnJZQkNoNTFEelVqeDJWRGhxbDgKKaTrEX43+XC5bV3SOpyvRfJA0Sijykbk
            hzNneKd6s3jDN7lKWb9n3ZPP39COsfxVRqmhGdi/tWsJYRC7+ljzRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hw8r4fnhy55rmvkkrm6lunh5wpmgl6dlam6mhcaxwtm0udvy9u3q78jxgq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T16:12:13Z"
    mac: ENC[AES256_GCM,data:weqo3RojZmBly8f+XQI1C1B+Ufg2aXSQ4tE6K+yH1IxrTNZU9kSrHLoJeDcJ1HKj3Wk2DloilsNXGdQZXxaMfX4dAAYceD/M3O+I0WIX/wm9XMnFpbjg/H7MFuuOphKskHcN6Fcr0wsmrISL8mgrFSHpPW6jt8DM4l4Hv8lxFFQ=,iv:qbHjvWYHflsfGdK75ZnJrCzt/KUA7VDZ831AvVb2uwQ=,tag:5tOghkXAsa7CdFDFeEQZLA==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
