---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  interval: 30m
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: rook-ceph-cluster
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    operatorNamespace: rook-ceph
    cephClusterSpec:
      external:
        enable: true
      crashCollector:
        disable: true
      healthCheck:
        daemonHealth:
          mon:
            disabled: false
            interval: 45s
    monitoring:
      enabled: true
      metricsDisabled: false
      createPrometheusRules: true

    # -- Settings for the block pool snapshot class
    # @default -- See [RBD Snapshots](../Storage-Configuration/Ceph-CSI/ceph-csi-snapshot.md#rbd-snapshots)
    cephBlockPoolsVolumeSnapshotClass:
      enabled: true
      name: ceph-rbd-snapshot
      isDefault: true
      deletionPolicy: Delete
      # see https://rook.io/docs/rook/v1.10/Storage-Configuration/Ceph-CSI/ceph-csi-snapshot/#rbd-snapshots for available configuration
      parameters: # Only pool needs to be specified as snapshotter secret and clusterID are already pre-selected
        pool: K8S

    cephBlockPools: {}

    cephFileSystems: {}

    cephObjectStores: {}