---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: rook-ceph
  # maxHistory: 2
  # install:
  #   createNamespace: true
  #   remediation:
  #     retries: 3
  # upgrade:
  #   cleanupOnFail: true
  #   remediation:
  #     retries: 3
  # uninstall:
  #   keepHistory: false
  values:
    crds:
      enabled: true
    monitoring:
      enabled: true
    image:
      repository: ghcr.io/rook/ceph
    csi:
      enableCephfsDriver: false
      serviceMonitor:
        enabled: true
      csiAddons:
        enabled: false
      enableCSIEncryption: false
      enableVolumeGroupSnapshot: false
      cephFSKernelMountOptions: ms_mode=secure # Necessary, otherwise PVC won't be able to be mounted to Pod. You'll see errors like stderr: unable to get monitor info from DNS SRV with service name: ceph-mon, failed for service _ceph-mon._tcp
