---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 4.5.4@sha256:f0a74313d750bc437ba2ad34f3412de5ab9a978f3f5b74227a1bda69271fef3e
    env:
      TZ: Europe/Stockholm
      QBITTORRENT__PORT: &port 8080
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: "download-circle-outline"
          hajimari.io/group: "Media"
        hosts:
          - host: &host "qbitt.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config
        mountPath: /config
      downloads:
        enabled: true
        type: nfs
        server: 10.10.10.30
        path: /volume2/media/downloads
        mountPath: /downloads
      media:
        enabled: true
        type: nfs
        server: 10.10.10.30
        path: /volume2/media
        mountPath: /media
    resources:
      requests:
        cpu: 10m
        memory: 79M
      limits:
        memory: 1806M
    podAnnotations:
      setGateway: "true"
