apiVersion: v1
kind: Secret
metadata:
    name: kopiur-repository-secret
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:afJtXv8vweDCoyvDYC9q0cqli5s=,iv:FL60uMiaEdt/wN0NFB8lLT3QQcKvoUk9NRujRChAzaE=,tag:9xnwT59/7SFakrUnpzVbqQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZuVKNvtDwbAtZcA2nN9CkkF1eQGxC5IAXcPRy1ztDm85Mc2Teb1ZDg==,iv:uMlFAU0F11TKNXJUCOgtT4vx/7cgPlv/R9iSnWNjj0c=,tag:71L05+gii7C9D6tCPYwgVg==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:2vvbQuSMMnB/2r90Qm5EAPf2onOW2oQR,iv:igRj/I7s4Q+EJ5CWQziFH/BLbPaPlFrtL7qRPK2Be3M=,tag:/7ibto7qYQpn2t0nsr1zfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5em9yZko2b3V2S0ZkNnh3
            Qk9TQmJYRjlKYVdBcXZlQWxHckp3blU2Q3djCmZSQjZNZjJtTXRIcEpQYk9DN0x6
            a0FNVzl1eFFIVUJpd0Y5d3l0eTZsNFEKLS0tIDZuVWZnTkZSR015Vm1wRm42V3hX
            YlZUSlYyT3hSVVRBc0djbk52QVBhaTAKfZFjC9yvXpXsRhUbBjRJcCfwPGVwlADk
            zbzgHdwdguwtqLwgZk8cVs+K4Vzna7xTFn7hJzt9HPuTv3OKUQ9V1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hw8r4fnhy55rmvkkrm6lunh5wpmgl6dlam6mhcaxwtm0udvy9u3q78jxgq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T20:44:22Z"
    mac: ENC[AES256_GCM,data:bSnRlMMR5kM/oc/9FzzxxnsnRPCATsUgaPH/ymmgBIdsdReCD+l/qwDPAunycgPxR38goiiBxjGQlRjtoVQW4omUeVr4I/8azmZ3UNo1qtFtN8AOeAufWzvlbr1S9oUs6HIhY3IFgWbxjmNbWjzdJuxjYE1bJTvqA4K2gxz9HOM=,iv:VrNDwH4eF/TUe4fugznzCvFwQ2AJs2RYVhz5vP2BdfU=,tag:G98AVGgjA9cJoIo3sVm3pg==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
