---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age150ce846uvyh0vlyls9hven23e8xzh3sqj478hzevx4yuyremh3ss2m9svz"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age150ce846uvyh0vlyls9hven23e8xzh3sqj478hzevx4yuyremh3ss2m9svz"
