---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app nextcloud
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: nextcloud
      version: 3.5.3
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: nextcloud
      tag: 26.0.2
      pullPolicy: IfNotPresent
    replicaCount: 1
    ingress:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns.home.arpa/enabled: "true"
        hajimari.io/icon: simple-icons:nextcloud
        nginx.ingress.kubernetes.io/proxy-body-size: "10G"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        nginx.ingress.kubernetes.io/server-snippet: |-
          server_tokens off;
          proxy_hide_header X-Powered-By;
          rewrite ^/.well-known/webfinger /public.php?service=webfinger last;
          rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
          rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
          location = /.well-known/carddav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /.well-known/caldav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
          }
          location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
            deny all;
          }
          location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
            deny all;
          }
          location ^~ /.well-known {
          return 301 /index.php$uri;
          }
          location = /.well-known/webfinger {
          return 301 /index.php$uri;
          }
      path: /
      pathType: Prefix
      tls:
        - hosts:
            - nc.${SECRET_DOMAIN}
    nextcloud:
      host: nc.${SECRET_DOMAIN}
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
      defaultConfigs:
        .htaccess: true
        redis.config.php: false
        apache-pretty-urls.config.php: true
        apcu.config.php: true
        apps.config.php: true
        autoconfig.php: false
        # SMTP default configuration
        smtp.config.php: true
      mail:
        enabled: true
      configs:
        custom.config.php: |-
          <?php
          $CONFIG = array (
            'overwriteprotocol' => 'https',
            'overwrite.cli.url' => 'https://nc.${SECRET_DOMAIN}',
            'filelocking.enabled' => 'true',
            'loglevel' => '2',
            'enable_previews' => true,
            'trusted_domains' =>
              [
                'nextcloud',
                'nc',
                'nc.${SECRET_DOMAIN}'
              ],
            'trusted_proxies' =>
              [
                'nginx'
              ],
            'forwarded_for_headers' =>
              [
                0 => 'X-Forwarded-For',
                1 => 'HTTP_X_FORWARDED_FOR',
              ],
            'default_phone_region' => 'SE',
          );
        redis.config.php: |-
          <?php
          $CONFIG = array (
            'memcache.local' => '\\OC\\Memcache\\Redis',
            'memcache.distributed' => '\OC\Memcache\Redis',
            'memcache.locking' => '\OC\Memcache\Redis',
            'redis' => array(
              'host' => 'redis-lb.databases.svc.cluster.local',
              'port' => 6379,
            )
          );
      strategy:
        type: Recreate
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: postgres-v15-rw.databases.svc.cluster.local
    cronjob:
      enabled: true
    persistence:
      enabled: true
      existingClaim: nextcloud-config
      nextcloudData:
        enabled: true
        existingClaim: nextcloud-nfs
        accessMode: ReadWriteMany
    resources:
      requests:
        cpu: 150m
        memory: 512Mi
      limits:
        memory: 5120Mi
    livenessProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3
      successThreshold: 1
    readinessProbe:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 60
      timeoutSeconds: 5
      failureThreshold: 10
      successThreshold: 1
    startupProbe:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 120
      timeoutSeconds: 20
      failureThreshold: 60
      successThreshold: 1
    rbac:
      enabled: false
      serviceaccount:
        create: true
        name: nextcloud-serviceaccount
  valuesFrom:
    - targetPath: externalDatabase.user
      kind: Secret
      name: nextcloud-secret
      valuesKey: POSTGRES_USER
    - targetPath: externalDatabase.password
      kind: Secret
      name: nextcloud-secret
      valuesKey: POSTGRES_PASS
    - targetPath: externalDatabase.database
      kind: Secret
      name: nextcloud-secret
      valuesKey: POSTGRES_DB
    - targetPath: metrics.token
      kind: Secret
      name: nextcloud-secret
      valuesKey: nextcloud-token
    - targetPath: nextcloud.mail.smtp.host
      kind: Secret
      name: nextcloud-secret
      valuesKey: MAIL_HOST
    - targetPath: nextcloud.mail.smtp.port
      kind: Secret
      name: nextcloud-secret
      valuesKey: MAIL_PORT
    - targetPath: nextcloud.mail.smtp.name
      kind: Secret
      name: nextcloud-secret
      valuesKey: smtp-username
    - targetPath: nextcloud.mail.smtp.password
      kind: Secret
      name: nextcloud-secret
      valuesKey: smtp-password
    - targetPath: nextcloud.mail.fromAddress
      kind: Secret
      name: nextcloud-secret
      valuesKey: MAIL_FROM
    - targetPath: nextcloud.mail.domain
      kind: Secret
      name: nextcloud-secret
      valuesKey: MAIL_DOMAIN
