---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  defaultMode: 0755
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
