apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: home
stringData:
    nextcloud-username: ENC[AES256_GCM,data:m8BT9PyRIQs1mQY=,iv:dLBqT+KGdOUvrt7Hp6mfquWHZd9JkWQqJUS51Tf6FdI=,tag:YylKpxNLJZDodl1/LG+psw==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:6I72sY/EscWkU4U4CVxqkEP0m70uz8OeXVbSjg==,iv:tldFcthp6BRI54pwBdrEWS0plNTj7u3q8fW5GaT61zU=,tag:VKNCRIpEGtFusF/AFHgFsg==,type:str]
    serverinfo_token: ENC[AES256_GCM,data:2jrX+ORXxpS5CNrTfX1Q5Ph+nT48oOaEgInH7I4/rJPK7qdvlx4Cv9y2X8bxIWWIKAZuiD4bKL+ZOrorEHDjcQ==,iv:kdwljMuunRi3lLoLC3idS+rrH3Ew/BFf+2yL37jxRGQ=,tag:46K2lxu0WUHXK1VSB6qTqQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:Fz6tWQ==,iv:tTbNgHeS4sm9p2hmYiXMJtc2P8fNKGKW7RHUIDegdyc=,tag:udN81nS8fn1KjnjOLoi4Cw==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:Lo8zJvn6ZUh4RNv7L/UIngEOM96zAGhkRe5TEnnviwxlKiYyrFs+mK0VwA==,iv:cWTYxfwO45BX6vdo2maZ1R54wsmRcCzM7miJZPqfNwU=,tag:iK/zSd7qv6py4u19YiRhHA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:GH69b8N8anc=,iv:jmxQLLbld/0PzE3LTuAOf75TzniZm2jj9DQFhdG2foc=,tag:Q4vkpQI3qMoPogVUbhV2fg==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:hPef6Sz4nqlRuqov9NcHrSlf1Zc=,iv:cacsSCykh6AnfIFb28Tk4ys60bmlsbeGJAjIkCAwzDY=,tag:EYLEA9DAMqSs/sigtfryxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y6admte6g24crgupz4lpaszp0vxr9nntyjprjk27trp9ustvzumsml44sg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNFpIbkxBYm5LbXRyZmtw
            NnMrUGl1cml1NEhYZ1hXS2JnaWlWemxlM1dvClJFN0JsUWJnVzc1MG9vSk8wYlV0
            eGtSam80TkhEcDhQaE1KWEdvWXd4RnMKLS0tIEtIV3dBdEZndVJUT1NZT1dIM0hP
            VUQxK0ZQRVNTdllzODVkaFEyTWNCMjgKMmcP2fKYSlNwFEX4X5nVKI9QVKpjvmaD
            Uj68XFd+AbI4sot+0ECVI+hb83QG+WSHneBZEkbnHBeDqIbJ2eBlPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-18T23:41:00Z"
    mac: ENC[AES256_GCM,data:GDNfdIxvYcuEXMup1ZfjbCm7SI3bWrPd1lQ6R1L/2lcCcv6tiv8DHXnQxJax9K9Cg1PAVat2wFfqHOoy0g05SFe4TY2h0GYvXpWL6ykscqIk0IQk5ZLq8FmKm0t6//1wUnlwBOmRkyM55n2q54z+IzLmDVNVjuMsohmDj0ZTH10=,iv:oWFN0R7mMky2WG1XVFJYijD4JD9t0CaDyW/p9R3xXxk=,tag:tWatrWvnU0vI5BirMmnhpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
