apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: home
stringData:
  NEXTCLOUD_ADMIN_USER: ENC[AES256_GCM,data:65tOEig=,iv:FIKMeBFtnLI9ejwZXRcBqYOAX9PMRbsMyEVpadDraI8=,tag:Wxh87eeSSMtk40qqoue10g==,type:str]
  NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:L5lwfKMVIXpJ5CPug4MW31H7tmDUzEva3LrYWtdguQ==,iv:Uxc6/2MKbPCslB2wQWOAXO5zgwf1mskQXmE74EegVWM=,tag:groM0HEIVNhJpsNlfizXCQ==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:rn/s4eOynlC8,iv:Q1jwMlqQ1gIgMaydPXgFqHKLmVVIVOJXLLuTiYbKU6I=,tag:jqArzdeeMZgfP7YcM8raaQ==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:LxTtFpPwclRWFEU1+m2YYZYMHgU7EiTOyR/Qz3QAEjODfmg0xP5tAav0fe6Ohpub,iv:r8pLkn9WT9bl09rCU9BD6PUovsYMC9Mb7n0tcEuBmuM=,tag:3Bq9U1bh++GdFNPbJ43MTA==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:PYlBN4tbolbl,iv:FliY1vAYz1dj0wCQWMM2LLcbzRYIr+/gpy8uO+RQEfk=,tag:Fb2lR8FC73579qvQeigEoA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:u9BRYTCfq8z9dic2wBWpur6LyfBtvPQN2Hn7fwRBNbfuJo65l6nx,iv:RjDBauFWE8m6kihP+2/gmyzCfOfiP2euBpFZoV/55Zo=,tag:pblrzQrl1CPfa+56XW++9Q==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:sVd9M5C03Su8,iv:V9MiAgxQHnAkBg0IJZGz9l8ymBd5+DEeptVg8k4VRuA=,tag:H6WWsIIGsWaxX1Q/SZyToQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:6yKceEXYdol+ODjxqXZpsmXzSO/aGsK4Lxut1yxuBuKSdQ1/jT0WDsGijVQt1v44,iv:OuPUIq9dAebOq3+vbFFx9BPdJA/CR80ag8q2dhcdzqE=,tag:xmbqKH9SEXBgZ0w3HlYEsw==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:9lMLTjRi6Qo=,iv:4ImhWOdboWNjSLDaSUZknV0VAZihznQAh4SE3w3qmgU=,tag:tTICu1LKOAmbmk8ju7cGeQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:ZeWBx66eZmVDOWSw9gzUHwMhz5eQ3S0v5UxY6DHlevHh6gm6i8gn42DkwFma/vqcUlLplMl4zIt6l80G92mizw==,iv:dhX/Wjw1TSE/QEzu5GWO6d1nLy7SEsqAwbBOedSpIyY=,tag:AjZI6Ol/y9oD6TS9/Y9eng==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnazY5VmpmcERaVkVxeXNY
        R2pKSDYwTmJtdTNaaGNCS1RFclB2cXgrU1NnClZzVFYxTTZEbHYzK0hhRzRMZU03
        Yy8vYmFYV1VqaUI3Z2g1bnZyaFVWcmMKLS0tIGdrUUZMcVJZbTVKV003WkE3NWt2
        cnlGbW1icDJHV25MektBdThhQlhFRTgKo1ERt2NBPILwMKBKj3ytoeIvtyV7jwMX
        7Vzz71Mvm5uW8uk7qO/7htO9/9XKHOmzOsw3R+o+t5ysQyAxhkce6Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hw8r4fnhy55rmvkkrm6lunh5wpmgl6dlam6mhcaxwtm0udvy9u3q78jxgq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T19:18:15Z"
  mac: ENC[AES256_GCM,data:WiHYcut7MYgwhuzZuQi84DkrtSqfrhcSW2T+Kc/HptjPbvPvBjlvzmAyhSK3CMep8dBWz+MrW7tTgNaQfaU3iR9dWj2G5ZDD9wDeIfFGn/fxv3wswawpRvzMncl6RcdTIZDLTLymTvHGkOo5959vTfenJphecDvjQNKs3qK1R/U=,iv:wxi/c2FFhjaYYjNvjyIf+W4LBZoMtrP2UvkCPZP/RNE=,tag:E1LiLDnBnjAYHxa/V4aV0Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
