---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-logs
spec:
  dependsOn:
    - name: grafana-operator # provides the GrafanaDashboard CRD
    - name: rook-ceph-cluster
      namespace: rook-ceph
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: victoria-logs
      namespace: o11y
  interval: 1h
  path: ./kubernetes/apps/o11y/victoria-logs/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: o11y
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-logs-collector
spec:
  dependsOn:
    - name: victoria-logs
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: victoria-logs-collector
      namespace: o11y
  interval: 1h
  path: ./kubernetes/apps/o11y/victoria-logs/collector
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: o11y
  wait: false
