---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-opensearch
  namespace: flux-system
spec:
  path: ./kubernetes/apps/monitoring/opensearch/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: opensearch-operator
      namespace: monitoring
  interval: 30m
  retryInterval: 1m
  timeout: 3m
