kind: ENC[AES256_GCM,data:HpfFPP4e,iv:1wTITE/NQutdoskMnQ70yCIS88tfEUzkIs5QBVoQk7Q=,tag:xGhUDuHyTYgAWc+yA0jAIg==,type:str]
ansible_user: ENC[AES256_GCM,data:gHuns17bXRre,iv:dmaspWha+yIljIrAY2HwtR4bEnFUj0L46qAkb/Cj4rk=,tag:WM1+akA8vbLiFxNw4BVkQQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:PORJ00QTRxIP4Hus+98OZKYL3Cw=,iv:EBVtICdKNj6IoJQuHAO3NQQcCsYPlD+WbM3I7B70wPo=,tag:A1CakEdUrtx7eF0UmVT6yQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y6admte6g24crgupz4lpaszp0vxr9nntyjprjk27trp9ustvzumsml44sg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudkFrOXRvOGlzc2w3QTJu
            L2hjZHJ4TTZqQlMzOHhFMW1JR09yOEx6T3dNCmVjd3VWVkNlejJpdzZNeWliMitw
            S2dRUEt0QXZoVG9ha1o0SlpqMHMrbzAKLS0tIEl1bzJ2WnVId0o4c2l3aElHZXdI
            YXFITEZhM1JtaENCMjlVUUpTSlo2Mm8KFZ8mr0/aMn4/yZWsXku6uBLUn6dbpZRN
            MbJfpwGHjSFdV0AwjQrTci1EsxrPTGwOJc4VWCZhlSq5Aa54d/Q5jA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-09T18:46:56Z"
    mac: ENC[AES256_GCM,data:qEPUcOh+mqXpou85E6kNs0aBzZmV2lDJ1ft+9F2dDe3OrtQ2hCdTLvB5D4SXKdUnk8baEmiGEYUlRtbD9yn8DLukWzjdnbvO5LpEygzDLK1pgtDaYJkpWKJl0Mohl+6sNNZOtmoAXmIl66tNVaPVuxF8K8F4dPdmHrn3fYP9woA=,iv:APbhVKuNPHbD3XGcBnuQOJflnYo5lhNdzcq16otOTPo=,tag:msFbJ//DYqUZCkOVNy6puQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
