---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open-budgeteer
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    initContainers:
      01-init-db:
        image: ghcr.io/onedr0p/postgres-init:15.5
        imagePullPolicy: IfNotPresent
        envFrom: &envFrom
          - secretRef:
              name: open-budgeteer-secret
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: axelander/openbudgeteer
      tag: pre-release@sha256:d71fd1ae742e59753f042217cf969b086ecaf052168c57d51f004607a264ce1e
    env:
      APPSETTINGS_CULTURE: sv-SE
      APPSETTINGS_THEME: solar
    envFrom: *envFrom
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: "currency-usd"
          hajimari.io/appName: "Open-Budgeteer"
          hajimari.io/group: "Home/Web"
        hosts:
          - host: &host "budget.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 750Mi
