apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:pBW/SN5hIxIwoVixghKesLLrmLInLUfXxqtt9v18VW9X5fdp,iv:M3bBOXOIgauouvpykJo8Ggnsv1eXsSlilclGCg0pvlU=,tag:5K6Mv5vNABB3zKnZ3XgVgQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:3ctPsMkyeder6LTgjauu2xz45KdTh3UetrfUT+eMvSnP2mOx1yoqClRIKpZZkmbEe0XnZN2kHK/LlyqRiSbAK5UR9svmN7V0iWMOoNEhOgT1aU5Hbnqm72VJdQjx+NC4C02WEzGTiYUKWn9UXSpUV4IoRI5cOb4es6y8L8YhH+MbQHSce4Sfo4FlM81UdXJijy9k/h5b83kwBHXqRC1XxuSJCJvaYkIDGdw0j01vnA==,iv:iJvuYtyywxLjvg/fGOu/LLCvOxhccOzM7hP1UHeWet4=,tag:VvhW4T77Kct+2v1gJ1eELQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150ce846uvyh0vlyls9hven23e8xzh3sqj478hzevx4yuyremh3ss2m9svz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWXk0Zy9EZ003WEJ1YzVE
            TzVDcm1GVmU2bzhjL0x5a3NOZVQrS0RCVDN3CkdtTW95ZXBONVdwRmdWQW9tVm9H
            ZE9rRlQ4SmNPYXZDa2JRWEFxcTQwOHcKLS0tIFFoemI2NGlsQytsbVFYUk9qeFVC
            Mk5PK2V2YzlUK2ZtTXpMOUNzMks5M2sKFcHXFyKw6NsxnhivbqT3mXoNkCmTXbVp
            3ShQyFjZIrAXF/RK+KkR7QsR8QoYp49eNU6RNnhBb+PbZ3ZyNaYt5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-07T20:56:52Z"
    mac: ENC[AES256_GCM,data:P5YOGWrnfHWuRz7lh4/CyzJM+i7U9W0hfMtGBJwNu+d6sgeIf79PZK4Y7EPGD+CFyizKNJ8MU7vnBmFAmOcB7BZ3NpJFcV3gXkSo1CmpAwGE31ckVblFlFvn+RG5xmxlXT328DjK+9uB4nLVAS0ejT0/Qtd+NKXerRWsJSWtPb8=,iv:9mTgEJ4ZKiXhNqJVD43Pes5ZJi6rqk1/XHJ4ycxM+Nc=,tag:NepeBUHew6a/1o9rmd71ow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
