apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:pA1r6MvHXivwuJ8W+CYwFCWmU7jfjPjBIJN+UeThh/MC8r6b,iv:mvfQjTsdbgbhthkp3nNVt79eIHfwl/INuncOL6YjIoY=,tag:3r/RcmGEf5rPI+mEz+d94g==,type:str]
    credentials.json: ENC[AES256_GCM,data:9lzYkeIa+hIAxJbj3T8t7AdJFKGlVLGLZ2e2y/kE5SYlH7tZ+6eupLfd4b/Oyl5XCYezlYSvXnLH3Ra1iA/nM3DeeIKMwQ8+PjjOIte6HbNt5k4wf2lrYxwdocVU3MgyNhj+Vutdgx7DWhwtxcIveCE9g90LCsh4F8s9zldB/UTmjVePcRrg8ERfW6mlT3xOF+P05+wGaWv0HNDyrZYILXA9zbs5TNtYCs/EnDR35w==,iv:fI6ucuW1YCUAJQyf0s2vP5bMtCNaUKMCBvjs/KDjJhg=,tag:x2lcezTIRkTl+lv4NhhpVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1penp3cgk75mq57r3ytlqgxa53vh2gvvwx2w3q688gpxg4p6v4p7q7jkpdn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0T1ljYkc3MHN1aExVREpk
            dkFBdW50U05aTjRGMldieVE4M2xWWktGQW1zCktzc1YyTE1aWW5lTFVXY05vOExl
            RjkwMmtSRmFXWklHcW5XOThjV0NFcUkKLS0tIGlhWjJYRGM5V3V3TCtaWVZCQ0xX
            MFZ3c01SOWsvblpLQWY1dm82V0JXRHMKaWhShq76KjUeU0HNnnDA0GqLQxUVjjwH
            vb1xg9J/+S86OFntVFraM+tFb06iuLeFDZwlzADen1p5jctoGtPHMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-08T18:10:59Z"
    mac: ENC[AES256_GCM,data:GnM8AkHn+PtBeQJrQdzJnzAriy98w36C2CwXErXYRkiTFJ/HRAi7xcrMnsw9XszYCtXRsEoEOTvZxqzUNhucyJEQJOXezDtP3LKiaduN5D2WPcjif7rnClLu0feHRfPswDZnZsHzWc+BLyQvYoAx+Lygd1uaT0fM2rLCsvwsolY=,iv:O7kTDzJ0l2/lec1+IXrG2Yr4Rdb933GCCn6RzBowtRU=,tag:E2kbLkvpvowvM7+GMKOd+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
