apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:T8g3DogLl227utPRw+GNfpZX2PfmIOHrScwZBizwl40Pol4M1OSqVnA+3tP0ANWwoipIRw4=,iv:KAQTBJrupTnt+0ft4rnkQLXzHlYLlGfcPIo/+eYjZY8=,tag:J7GP+03SnmJYtZdd99uN3Q==,type:str]
sops:
  age:
    - recipient: age1hw8r4fnhy55rmvkkrm6lunh5wpmgl6dlam6mhcaxwtm0udvy9u3q78jxgq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWXNQODFOMHVDaVlsSEpZ
        Qzl5NE0wMXRMdXlzWVU3SzJzVlp0dHNNM0VnCkRTL1BGS3ovaTNGL0N1WUN6bGRw
        WmdGU2dHMmRjbloxdDZWb3k2TnFtd3cKLS0tIExDV1N6V2p1WXRNMFJTTkk3a2U5
        R2pxZjcvbndUNXZaSEtONFlhQkFwMkEK/P14Ubm1wqAgFll0PlBqK9qSm+g6mQ2V
        Qf9x/mmZtTjwKNrVlbUUaq3G0ANXN90mFGZFylpiZUdOPrWn4mJZQQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T09:45:19Z"
  mac: ENC[AES256_GCM,data:mp6iShzB+25/4HvNNX1RdowyQZeLHvZ7IM+1hdCdgwplgEWmD1wTw5oVldsbkGFkb8L5cc4wIAfG3rIhKmQEvonzvlor6D/SWCQl1gNrg40VkaPWQA97stplqi8uCVECU1irKLBWurDverBeHnbrXBi33k71OTyaYnSXkqkapwE=,iv:MH5o1w5G2FZZjoyfUf7HGFlIzVPu5MXinbgOzzTX1CI=,tag:ipup82LAACIM57iow9CJ/w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
