---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: grafana
      version: 6.60.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    replicas: 1
    rbac:
      pspEnabled: false
    testFramework:
      enabled: false
    admin:
      existingSecret: grafana-secret
      userKey: adminUser
      passwordKey: adminPass
    envFromSecrets:
      - name: grafana-secret
    env:
      GF_SERVER_ROOT_URL: https://grafana.${SECRET_DOMAIN}
      GF_AUTH_GENERIC_OAUTH_SCOPES: openid profile email
      GF_AUTH_GENERIC_OAUTH_ENABLED: true
    grafana.ini:
      analytics:
        check_for_updates: false
        check_for_plugin_updates: false
        reporting_enabled: false
      auth:
        oauth_auto_login: false
      auth.generic_oauth:
        enabled: true
        name: Authentik
        icon: signin
        scopes: openid profile email
        empty_scopes: false
        use_pkce: true
      auth.generic_oauth.group_mapping:
        org_id: 1
        role_attribute_path: |
          contains(groups[*], 'Grafana Admins') && 'Admin' || contains(groups[*], 'Grafana Editors') && 'Editor' || 'Viewer'
      auth.basic:
        enabled: true
        disable_login_form: false
      auth.anonymous:
        enabled: false
      server:
        root_url: https://grafana.${EXTERNAL_DOMAIN}
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: "default"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: false
            options:
              path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        # Ref: https://grafana.com/grafana/dashboards/2842
        ceph-cluster:
          gnetId: 2842
          revision: 16
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/5336
        ceph-osd:
          gnetId: 5336
          revision: 9
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/5342
        ceph-pools:
          gnetId: 5342
          revision: 9
          datasource: Prometheus
        #Ref: https://github.com/fluxcd/flux2/tree/main/manifests/monitoring/monitoring-config/dashboards
        flux-cluster:
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/monitoring-config/dashboards/cluster.json
          datasource: Prometheus
        flux-control-plane:
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/monitoring-config/dashboards/control-plane.json
          datasource: Prometheus
        flux-logs:
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/monitoring-config/dashboards/logs.json
          datasource: Prometheus
        cnpg:
          url: https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/main/docs/src/samples/monitoring/grafana-dashboard.json
          datasource: Prometheus
        redis:
          gnetId: 14091
          revision: 1
          datasource: Prometheus
        unifi-udmp:
          gnetId: 11313
          revision: 9
          datasource: Prometheus
        unifi-usw:
          gnetId: 11312
          revision: 9
          datasource: Prometheus
        unifi-uap:
          gnetId: 11314
          revision: 10
          datasource: Prometheus
        unifi-clients:
          gnetId: 11315
          revision: 9
          datasource: Prometheus
        unifi-sites:
          gnetId: 11311
          revision: 5
          datasource: Prometheus
        unifi-client:
          gnetId: 11310
          revision: 5
          datasource: Prometheus
        authentik:
          gnetId: 14837
          revision: 2
          datasource: Prometheus
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://kube-prometheus-stack-prometheus:9090/
            isDefault: true
          - name: Loki
            type: loki
            uid: loki
            access: proxy
            url: http://loki-gateway.monitoring.svc.cluster.local
            jsonData:
              maxLines: 250
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
      datasources:
        enabled: true
        searchNamespace: ALL
    plugins:
      - natel-discrete-panel
      - pr0ps-trackmap-panel
      - grafana-piechart-panel
      - vonage-status-panel
      - grafana-worldmap-panel
      - grafana-clock-panel
    serviceMonitor:
      enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        hajimari.io/icon: simple-icons:grafana
        hajimari.io/appName: "Grafana"
        hajimari.io/group: "monitoring"
      hosts:
        - &host "grafana.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - *host
    imageRenderer:
      enabled: true
      replicas: 1
    persistence:
      enabled: false
    resources:
      limits:
        memory: 219M
      requests:
        cpu: 10m
        memory: 127M
