apiVersion: v1
kind: Secret
metadata:
  name: euro-office-secret
  namespace: home
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:UyYKxk6Mj+5v5qArgLQrfV8C/2w0TN5mJ3ZH0s8VOmtJIqFhcPzL9gR+MCybibItVz8khbSxsfnQebVespedHw==,iv:TLuTCSrj7IMx45YZl4xYCO6EIAcdXaVz/qXvrFEJo8s=,tag:9mKrrQcgEefavSxb3KmTzw==,type:str]
  SECURE_LINK_SECRET: ENC[AES256_GCM,data:72BIO4Yx5YoI/f+HaiHwXrffHmGPl3BkONHCR3HGXJQ=,iv:JRsGwc8oRprYX86aDFVdcF66IODhyludAmVU0cBfvII=,tag:7cVFHtIUDmaoqerSN9Uvig==,type:str]
  DB_PWD: ENC[AES256_GCM,data:OdPVFI2958yTn1M3zP8tc1Yqze5IT0yKsbis695Dt8XqmrKYprOPMlYAq8bK1Qra,iv:+4Wu88n7lTsvjwtAtPcONjVrzvZfgX5G5+l+4QWQQFQ=,tag:OlEOVs0NlUXUqnySMpd/Yg==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:eGvdRgL+T5Xb8Q==,iv:GgqTaslXXxwv28fCRb0xJAvxE3lwARY6cGItZdEcR88=,tag:9m6/35wF6XZZ1xghmWvfKA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:uWMkLFxVV+6ikrkwbg46YlfTNPE9+C8UO6JUsPJepGK3iPdcjsLJ,iv:AzNSiyyeCGZkDIpovaVtii1ROaUt4TFtUs6eR+gPZoc=,tag:G1H3COmUJFVKgIY0v7Ns/A==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:D5cJ8Clf8a6fZQ==,iv:ijYNBiHK17piRpBNZFSoNW0uBw6/IgmPoEjgYAhqOGs=,tag:dDU/zgikrddl2uJ53wLWbg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:KAocFcT4tWdZI2BXhIGYxe1hzFlYRQS75DhUALhrcZhISip6E1aFbN0ZsiDUnWBe,iv:8uw/k3mBfI49Ga6Yk/V4lu3pNNaknyKK1InbmZrZMfY=,tag:F8BNPyDM1i0KFAoXiz0Irw==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:OyboloHjXz4=,iv:UBT2DIkM/a9vkk7uayMCRlvtJ+mXGwLdihx1i2IFBjo=,tag:E/7+GEvBzhW3dCeA1UWerw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:GIrexS+K3EDJf0reuePfB6gcZLtxNs0j4sNNH/Qcb+C3if2LH8lVze9cTmRWVw3xZgBpV9aJeIqRlvqwUUhdBA==,iv:EY6ss1bqmKDcvn2toe/AIKShgLNYhfommjuk202T59Q=,tag:oI1yG4nZOypjwDbEep6Xkw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNW1QeUNXZmNzUVpNd0sx
        Sk00RC9tZzlzTzFvY3dFekh1RUN2bUVWNEQwCjZob2Y1cE5veHA4TTFxY2x4RjZN
        WGU4L25TM3pJQ21EeldNbGN4THRkY0kKLS0tIGhGZFhrc3JHbUowNGJYRGlsYjRE
        QzBPRXVRVHlNQTN3VUV3MjlJRzFKcTAKQr4shxwJsGfLAmLXUK3sp80DfYzDmRL5
        jU3UBd5xlfhxxdd4O0W4y5r4w3JO8QJeeTta46VCG8P13cP5grWOkw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hw8r4fnhy55rmvkkrm6lunh5wpmgl6dlam6mhcaxwtm0udvy9u3q78jxgq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T21:44:49Z"
  mac: ENC[AES256_GCM,data:vBwBI3R9RTk54tqjQO2jNXbFUoaPVTAqS0RVtATiz6jU7hOQ2DcD2syVMmr2fNHgUN8feR933/Q5aKFq4on8gOzF0Deb18UKGz2Y1OtsVPWBsPQiAiXc9ZsG4uVmip+WBPHhEOENVjeSQzDrrZBhfotExSbUl3+2df3Xqjv9UUI=,iv:agIGbN7yxImRTKNs8Ci8w7Qmprg3cMwQ7rIZebNricc=,tag:agR/KqUWzE10rVc1aD48wQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
