apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:23n4CH/EaRPsnQcXmN8=,iv:eoWXA5Gg2YImSx0Whz+zby/fHwILb2+6ReDa0GGYoTE=,tag:PYITglk1AKn7vYllvWUkYw==,type:str]
    ROOK_EXTERNAL_FSID: ENC[AES256_GCM,data:ceVoKzjmC5Yu6t8q3CZYcZoZMG5+k33Jo6reJnLdJI8Y2FH7,iv:vZcJpOgrxWqWrd0gUvgw21yww9jSKw2Uf2sOx0TQ8vQ=,tag:6a3dls7QcduzuWPoohllMg==,type:str]
    ROOK_EXTERNAL_USERNAME: ENC[AES256_GCM,data:Z8TL0Dtk7NrRe3y0HABxI45RgtU=,iv:fTENKdYfmAg1JytTD7rederIWSQmbtUwu/7OtZXVtoY=,tag:Ce+100kRT+cfZrG5a6H6Mw==,type:str]
    ROOK_EXTERNAL_CEPH_MON_DATA: ENC[AES256_GCM,data:fhRRXjGmsrZbz70dJDtgQAdn5yXURlft1hnnZ06AdVnTBXTUYs0RGnp/GwR98LRtRJnTuPXSZkbCbdJnDY6ulHE=,iv:W8KuKKZ9HUiEiX9Z87Zya3UeSWA6OAgVQGRrZ5HG4Ds=,tag:yDLpGslBU88cMj70bcRbHA==,type:str]
    ROOK_EXTERNAL_USER_SECRET: ENC[AES256_GCM,data:XmP0Gc/YSLRB1y33rA7F7kfQNRabZly47oAurHHfXwl5iamBwvL25g==,iv:IWXRkpspKWV6j2XSswbjCoCAWuqGB+cbfIoCFtdPkX4=,tag:2ocTRJ1rdA8ipwqL5TO+mQ==,type:str]
    CSI_RBD_NODE_SECRET: ENC[AES256_GCM,data:ngiYZerq4RbZ7NkYKsVA2PpaY2UoNilpq09ptXhx/2CywiAU5Igrvw==,iv:BrgayixeQCHkDalDfijy0tFyeHYjTNq2opieT99JaTo=,tag:tkUJDkJWY8+8JkQ4yi8LHA==,type:str]
    CSI_RBD_NODE_SECRET_NAME: ENC[AES256_GCM,data:EkyGc2y+Brz7hWsq,iv:Lb8W+UXrMcluXTJudZ/fy6sg1S20Sr1UWw6l7zM0iDU=,tag:9JJ9PRtNgeR0IyG6vKUbmg==,type:str]
    CSI_RBD_PROVISIONER_SECRET: ENC[AES256_GCM,data:YUvXz2a9Z0QnSqIDMOB79+q30cJXeEREmQA2ozOsCt/LkShrMETuew==,iv:rKF/ZdJ3dvOS2/G/pgQdtR5UsJFCNW49uJ+flfuvoCo=,tag:yjTG3nyOhDs9TnlkjoulgA==,type:str]
    CSI_RBD_PROVISIONER_SECRET_NAME: ENC[AES256_GCM,data:gjLtUeLb6xppZP7bSQr79MAtJw==,iv:Zyv1zQmhb+NDG/1+imLHQVjRQASJibMtvKik8dV5b+o=,tag:VAjmCbfCYe+8B+z+DwK5nQ==,type:str]
    CEPHFS_POOL_NAME: ENC[AES256_GCM,data:HV7KiIIozKFHLr5/RW5q,iv:Zl8OWrQbiJ1Ou5wH9p8qQGD4Nu2I/or308URBcTI8OY=,tag:wzQP0K60jvOSoZHbIaR8ow==,type:str]
    CEPHFS_METADATA_POOL_NAME: ENC[AES256_GCM,data:Ln2kylyM1JGTW1FUxT2DElh0WQ==,iv:Z6OASvl5lMzuI1GtBtc9TepNZZjvAM9+NG3CoYGwHoA=,tag:syNTPBKysjccVVMfEHU6AQ==,type:str]
    CEPHFS_FS_NAME: ENC[AES256_GCM,data:oNf2lYK7qaMdZQ==,iv:rub7I3Zp3ZU+/0dmElfw1elydGUZE9ySnWFF6sA9JZo=,tag:2i5eSPiaPt9C+BSxOACqLQ==,type:str]
    CSI_CEPHFS_NODE_SECRET: ENC[AES256_GCM,data:A4QaiEUqqsF72dADq1OWjVoGFeqQfXs6q8IwTwITA1fPboOtHH1Usw==,iv:z/HXf2U1AW3mKmn/C6UnMBxrE5fVPYl5VKqtmMVlbLY=,tag:TdM6UoSVClF/+FSbs8geqQ==,type:str]
    CSI_CEPHFS_PROVISIONER_SECRET: ENC[AES256_GCM,data:snnjQupx6lJTM3PWXYj8F3Wd1WRmEzmcAcGgU2WpIOje9pj5eXo0Xw==,iv:TdGNqKh7P5DcGb5YI+0n/u2sjv0PD6ajo5prV0Tz0ns=,tag:Wga0W+hMQS02PCG5vrW8tQ==,type:str]
    CSI_CEPHFS_NODE_SECRET_NAME: ENC[AES256_GCM,data:aavk8pQRx3NBdPSe55OG,iv:YVSC+YOVrPIw4457Fb/PNi036dmEhGbrB3MM2Y4mE8M=,tag:e4reaErgb4EoRSzRb+1HFg==,type:str]
    CSI_CEPHFS_PROVISIONER_SECRET_NAME: ENC[AES256_GCM,data:HySYPP46vz0XkWZUtIc2l9uQFm1i8Q==,iv:P2ReCwN9P3wVpF9hKTQlXXEIBLSYLfE+fsVeBm3qzC8=,tag:VZGmPipJb7FFlpY4KYyQSw==,type:str]
    MONITORING_ENDPOINT: ENC[AES256_GCM,data:ZDHoMPN5oFPQNt2J,iv:QhAJvAlDmGGiHsgab13eDIKF7I9BmddFkCtrlEWprbA=,tag:Qqk9OsOJ4Oj5x2QkDMOGHg==,type:str]
    MONITORING_ENDPOINT_PORT: ENC[AES256_GCM,data:928sLw==,iv:F18rzHG/ZqpqzTouIfFRf+UUCvyJo8evtl4dS6PtjwI=,tag:Q/GYsyOhxHaioRAgkrj1zw==,type:int]
    RBD_POOL_NAME: ENC[AES256_GCM,data:jCRe,iv:aw0Y5mV1ZkW6UfSpkUntwPs4sahWRFGRKi5jCxQnGJU=,tag:UJcf6tGIOPGLRsGq+92Gtw==,type:str]
    RGW_POOL_PREFIX: ENC[AES256_GCM,data:tD/p90gUcQ==,iv:RNq284V/M5RdcSN/Cj9SG68P1nGytohbTk8HPp4xk6o=,tag:ogAAH/xPsIcQK3rOLMYChQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOTMxTVdpRy9IM3kzN2wr
            cmwyTnpxalVqT2pCQ2c1RG5qN3RNaGovbERNCm8rdXR3SjdUMmVTcjJ1Tk0rR1VO
            ZWo3b3hCMWZxeTMvQXhrbXphYW9JZ3cKLS0tIHp6bW9ZUVNyVWJxM1VOdGxReHR5
            Z3dIMTNoNFdxQjlkMTZOcWpwdllGWDgKYbRhl7+VcPWK5OE2MRYGLrPYFbc2VZ1U
            FyFDCvWOgCq9DDkGVPBjRoIaHd4SSyZyVVytF97ma0N7NvXdsbsMuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hw8r4fnhy55rmvkkrm6lunh5wpmgl6dlam6mhcaxwtm0udvy9u3q78jxgq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T17:19:35Z"
    mac: ENC[AES256_GCM,data:0bM7COJZQ9EmbKhiHbq9VGjB89j7LEcsUePeTSqgcCMLwRyNOwDc83twuX0eAuWuOl/DielZSNO7c3JL83BZWmTKXTieF0UjDqbiocD8zuM4RGEaYWF7r1sItBzVtXkxqR+13OHtXpy8iaRwq8jLKB36fVn67aL98SXq4LZh6Xc=,iv:efz7uTRyAOudc1rcNfuXBgpILp7V9RCNZuWknSPF+uQ=,tag:4DWSytKstwmg7drpuhaBTw==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
