apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:23n4CH/EaRPsnQcXmN8=,iv:eoWXA5Gg2YImSx0Whz+zby/fHwILb2+6ReDa0GGYoTE=,tag:PYITglk1AKn7vYllvWUkYw==,type:str]
sops:
  age:
    - recipient: age1hw8r4fnhy55rmvkkrm6lunh5wpmgl6dlam6mhcaxwtm0udvy9u3q78jxgq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOTMxTVdpRy9IM3kzN2wr
        cmwyTnpxalVqT2pCQ2c1RG5qN3RNaGovbERNCm8rdXR3SjdUMmVTcjJ1Tk0rR1VO
        ZWo3b3hCMWZxeTMvQXhrbXphYW9JZ3cKLS0tIHp6bW9ZUVNyVWJxM1VOdGxReHR5
        Z3dIMTNoNFdxQjlkMTZOcWpwdllGWDgKYbRhl7+VcPWK5OE2MRYGLrPYFbc2VZ1U
        FyFDCvWOgCq9DDkGVPBjRoIaHd4SSyZyVVytF97ma0N7NvXdsbsMuQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T09:45:19Z"
  mac: ENC[AES256_GCM,data:eDfbNMvahHDsQtmqbGgxMFoGq90KdQlt8h6znUHJUT7495J1eoEvpLYSvk8Y2826fWZomGsdqzRJVoa6ZRDQa5r+Su9cFS/VW3d2b8SnPeAAawO8TumO48zpDWGOUErBrZ78w8GDnyWijVn2p9CyivWbub8d71wPq7fYWiGhQIw=,iv:8DlE24ol0ud9JO/vG8Y4e36YuT7Ii0Ot5tiYqjP41ys=,tag:xJYkoA9mkPpEKGYEzyUrRQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
