apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secrets
    namespace: databases
data:
    email: ENC[AES256_GCM,data:TQVrZVwTMChzEhZyv7uWb/KnO/r/aE/TAtY2A0IVQxQSIyAf,iv:FEiPWY5PRZ0T8uB9HsG0EThtYcyXh0r6NCYm8sayagM=,tag:44GvbSggBw1oLCoo/LK/rA==,type:str]
    password: ENC[AES256_GCM,data:PCeIBZqfCemhwwkdGVRlQtQVHfvx1b6C6nmosQ==,iv:Md3JaOcUVdyd7QI9yfVAdPvJMXXnhCnPzH5SEZtM+LE=,tag:hKZWri5EuhO6RVSSLv4glA==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:Nyv4awfBWW0Ow+ByXllquZthPprzFzUVcG2DJA==,iv:xdW9h42gJidO/bZTkohEWrvR7ILT+1kO1PVsP+UfIEs=,tag:VueiMW1NXCdpVrvHd7Y2Og==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y6admte6g24crgupz4lpaszp0vxr9nntyjprjk27trp9ustvzumsml44sg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUGlGeWhWV3hCejcvR2w2
            dmpod25IQjI1czlLcVV3Nm5iZ0NFZEJNZWs4CmUzcXBtS3ppV3lhWnp5dnBEcTVL
            S0NmK01FQTlYWHpkdWtPVzZjcHUzUWsKLS0tIFByUGZRWENySnlkcTR6d1lHcjVO
            RDZNSm95WXJObDRxQWZmUnJJekZ0dEkKgcXAaXHL6KoKSMHCdiXj6iJbld3KLBe1
            /2vJ72UVAoakmOGN16DSsFyGN78vj4+ZUwIiALb/rHN8ht0F95l61Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-18T11:12:58Z"
    mac: ENC[AES256_GCM,data:lJaYgaUP5a1sccR70CiSuWPlIdSJsAt9N7aGsaFyhIs58ebYnDZcP1qqd/tK4cgMUJue/XpDrM3jftCtBXw9W6g8B9CcdW5qC/lqCRcUNf4P3BqbwOCOGbFrY5hUJU06nqKHX6fIJVKCJI47w6dApI62deGaB8gstdjznkJyJxY=,iv:4ICjGdpZINiRFvCl2le7/e7GuZjzGJEBCsK1mhHHqiE=,tag:XDRoiThgK5jzHEPTvnJ28A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
