apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:QTTh0z3YXPhM8hI0tMyIAmGHCUm79DZ8dONaCI9HSXA=,iv:3OKBLgLqppY/po3xNT5q57llqoJ8tp9rvmSlnOjsppc=,tag:YW8KqHPISLSu/2UluPmbpg==,type:str]
sops:
  age:
    - recipient: age1hw8r4fnhy55rmvkkrm6lunh5wpmgl6dlam6mhcaxwtm0udvy9u3q78jxgq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnc3dpdmFtNjdVNVZwMDdr
        WmwzUVJYaU9kUFNHbEkrUWdhNWRCMFBZQW1VCnhjZ1J2ampIOUFBcUljbEJaVStE
        QWZsREsxbEx6aDlKd3Q1dkhFZ09naGcKLS0tIFVyOXdVL1FTRzd0eEJtN2xoNEFN
        OVQyRVA0SjZyRE4wVG1aYVczZGl0cTAKDqUh0MGNqG1m90mT/LpLWYBKvjGji3Bf
        oVmTI8YQZSJunR/MkdeAb5HSoQGXAShz/0Ux7i8pXBsp0rCY+8GcYg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T09:45:19Z"
  mac: ENC[AES256_GCM,data:c/d+MXNq9A6trd8z+Mc2qjDGlYzNHRagENPphKFrFGzPz0pd4DYouF8NgYuzELPthqAuLWlLWW7tl8k6UswE7BDEJMjO5FzqV86wDtFs6g6WZTajEPc3mBZHIXHj+MztyfRdWqhjydzEovD4cVHhnTYz/lP9eItSp5c+9hdT7WU=,iv:Ti1yQ8WIZAWRQPOhaG1P119BJvIcw/2qBbYYNQyVl/o=,tag:wI/HKi+6FouHyjBOWGpF9w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
