apiVersion: v1
kind: Secret
metadata:
  name: eneo-secret
  namespace: ai
stringData:
  POSTGRES_USER: ENC[AES256_GCM,data:OvaAsA==,iv:lH0MgBIE8ojsme1oJqbcEDYIHMRnB8yIA4HzafJCPUg=,tag:H56emPgXIVNbKlRmYbWpGQ==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:y3dAyUuvgdZ04RvbQXsdkPKJJWq1Gh1F/Vr1qXW7a2LtJI7QfpCxFTn3cNJqiUa4,iv:puI3UEU7U1sa/o/VxaF4uOuG6aEVfSJEP0khdA1OKQc=,tag:6BpM6rcKY4gBsMLXoh8IVw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:v58Dhw==,iv:Jtn+efa+aMNB0rNbTHRaP0n2meQUCHEtlWFaCXj5Tas=,tag:4Egfq0XS/EhVgMvjuaVKow==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:z2y12B4GRc7aJDyTL0BUxFso2mCZ77vbcLc/Hdu2hdXbV6AmUNc1,iv:DvBdw5mQUXvmSZHXetkDNXqZ1p2ZzrAWuB5pYkXEEF8=,tag:YVWBDzWUA+S2VzUP2plANg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:qpACeQ==,iv:IUk27cLRpvQGaWD8ulLThZvwMD1lohHPnVlYLY0HN6M=,tag:mqUgwIIdpNNKsZ0EI43VYA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:det74NpyQkgU2Vc5VkBKwczzLqaoFnZeAe5VwuZHBm0hrsvVpKF37gS5xWq+fVHO,iv:Y9l+IGwPm5Ul5f7Z+tKNn11mjdP+ddaTFBqXPLo2uo4=,tag:kQH4SrIDs6gMuJtti19soA==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:dBaV1c5hLvI=,iv:YGOGwMYudrtZqrQbSH3w0XKoLjRX+wAxFxdUC2OOM8s=,tag:J4sanBxIb+7oijj9Tfi44A==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:zJGv61+ykIUkJuNcyL2max1MI3H1MIRKxf7Wj43WjpXVkPXFUB5W7eDdE9NzhRLhaBZFCwy3iEdqD0Bdq5vmVA==,iv:o5IsLcO1aUL8XqaCA4ia+MNXEj8QAuPZGnst3cReTjs=,tag:xgrVEQjIkUaln1BTeANKfw==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:CIZczlnHScd+fttv+niPc6syf2v7wIzCgZDMhUv38Q6aFuPIRrZ5h615q5eFNbf3uL2KzL0mKDh8CrDf5agGJw==,iv:SN3/Y8ZKxaFSeOX6MqrTEsSYeH6I8j4lFR9OI96z2gs=,tag:F6CNwFWB1fPHijIlOryf5w==,type:str]
  API_KEY_HASH_SECRET: ENC[AES256_GCM,data:j2no39qm0mOHPKZwg5C+gz6zdYPelIBS76b2Hqh1sulmiDWvZ4AgIhAKj7hdKOSu4f9UloIybN7viRprEjHFGw==,iv:3FkJ7+6q5ytwvGPZ25Okx3r5NLQhJ4qfA+lrwMpDkU0=,tag:gvpCbEO/U1MsA8KuvuQE/g==,type:str]
  URL_SIGNING_KEY: ENC[AES256_GCM,data:+BR0i4m+CXCvf4Acj35V0aVvcOmKYLwpBB0I4mdrnksHMSI6DLG/D8kMkScNrwbNrW4DzyKMjOllX5BBXowh9A==,iv:A5zxxuxvTRoPdPWKjEdhfw3s8Qq5ZjL797H+5HeLEQ8=,tag:aHtViXq3oCktYZu976THNg==,type:str]
  ENCRYPTION_KEY: ENC[AES256_GCM,data:H+5w8N2G4NV6HhKBLicJHlPMO72lk995C/roRDLiviqsfREZJf2/SnR5t+8=,iv:+Hn/KIGPH8UTpaettGL7Btdaf3qdm3ba3TEPa4gRZmo=,tag:5WWuLbX747jvSMl4DFgDLg==,type:str]
  DEFAULT_USER_PASSWORD: ENC[AES256_GCM,data:Yt/Ja6auNZCr0utuG+Jlr/IMvYhdXHgV8Jyy,iv:7g1AwDQ9TGBI03jfmCKuUt/4Mq2hDCkdhRaaFjUx5ws=,tag:SnhuUuBgo36Q67MRgLRHEQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQ1ExQ1lPeGp3aTlQNGQ1
        QkNtdU9HVUd4WXlPQmw5cTZrRnFEazdKRUNFCllVNnpRTDQ1ZGN0QzlCZnEwMy9X
        TXM5SUtqeitUanNUOG5mSldZU2g2MEkKLS0tIFFDTCs4OWlzYXRKK2RSRGdESEph
        d3dZU2JGM2prbzE3dXg3ZzJUVy9semMKH5Mj+L65F29mlczV1ZPYZ7fMu55nRzgs
        1cUT8zNW5sGqQBVOP7aLKgUgmBT8n5H+x88wY4DAAKAiaalBgiY9mQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hw8r4fnhy55rmvkkrm6lunh5wpmgl6dlam6mhcaxwtm0udvy9u3q78jxgq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-03T15:01:28Z"
  mac: ENC[AES256_GCM,data:iD1W1Z3zq7Vd5wSrNjiLKoTjddq5BN/4NYSxW5S1CRu94bO8B8UhQFTYpMlUcr4eXVVV380tQJQyqSUhgiUVEaA2ddmiv2IVeXPcLkjbHOzpg4NouEZWYDj4IFzZmhPJVXtsQyi7VLkkQS5abjUbI+wtG33p7bN8b/F22jAP1Ck=,iv:edcagbsmPNEC6CEaVIm2Z5p9aVC7wrEADSQKUcz28Aw=,tag:c3/WL2EmpgQLA3XGYPXdlg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
