apiVersion: v1
kind: Secret
metadata:
  name: home-ops-runner-secret
  namespace: actions-runner-system
stringData:
  github_app_id: ENC[AES256_GCM,data:8O+2pHJO2b+FvcHopHg1JLLDBA==,iv:+o2ZOzSz0WvXdnKLy7STDNStMFgf/cnM5TBwAcDJ5ts=,tag:4YbOGI2HrzGSZktz/W2NQA==,type:str]
  github_app_installation_id: ENC[AES256_GCM,data:VTDmLTcsOKDsh3BI+Zj9KE0AWYsb3eVzirybQw==,iv:VVH2SFjUfFMFCY+LaL7FombS1P1XmMmmMgE7kAO9JYQ=,tag:uUOr2qYJACCb0XsvdB7qgA==,type:str]
  github_app_private_key: ENC[AES256_GCM,data:xnQ/oXOU+yUkiiXeIlG9EuxRAmNfPjqe4BV4wgQl0NTB3lkjGQ2lqIoPxXtIe6aTXgOZEw/CMyHaI4aFTl5mkQU/wqAkq/X+WoSLZiOFxTQQpjLmX+Nf,iv:YBLamXidCGB8gKYLQuKuk8UzNPIQanDsSS+zesWeLyA=,tag:/B7nT6vMh6REiMcX0Kv1FQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZ1pYZDNEVGxDbUttU2p5
        U2ppNXRSUllFOXZKYmpRVnNzUVo2RFRRc2djCjUyQnN1V1FIT2hHVUd5T05JVTlV
        VzA4QjV0WjU4aVZMZ3RXMnZtaG9MbDgKLS0tIEx1QVY0OHJsNGdOckFWVEFZaiti
        eDlNRlBqZHRhMGM3cTJFODlLZDlnb28KuiVUIa1lT/FyIZrX+znf07Nlp+04iTYF
        +Xqf0GdxQEiW+n7iumQ+sCfbBYxKNW5TT8XtkMRFSj2IjfNAGz+WgQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hw8r4fnhy55rmvkkrm6lunh5wpmgl6dlam6mhcaxwtm0udvy9u3q78jxgq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-04T17:45:34Z"
  mac: ENC[AES256_GCM,data:4oko0sYrS/iONf50ZF8IeaqBzpSJnVsWT59XM0CH0Q8SohUOYroXj8I0j14nmQJuJd7FjVgQlnEKPPMjx94SfT/6ndr51uTnJhjjtpZytpXZqSz23++Lzd88cKG7K2TWu/FcJA8uS7fyBZdQg7bTtf3idFZkIfYphGmHg3oj8vg=,iv:uZXk03Wcat4lcy0wBJrzhQ0M3u4dUdD1EYghBMo9naM=,tag:fBvhe9Adr5+G1HAB2zr+pQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
