---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home

components:
  - ../../components/sops
  - ../../components/kopiur/secret

resources:
  - ./namespace.yaml
  - ./nextcloud/ks.yaml
  - ./euro-office/ks.yaml
