apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
    namespace: media
stringData:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:tbkkZErtIk8AcYiuPMG5VDEMDmqTdgQ5nOkQKm0FSPc=,iv:QyJaDbR/308Kr1/hGyd6fO93zsLXscoEPvxQltMIXOA=,tag:gCJKD1+i7zgV5YiAt1lBuA==,type:str]
    SONARR__POSTGRES__HOST: ENC[AES256_GCM,data:nuwCUv3IYCg+bVXAsc9DKon4oB/QjmFz2k5Xqzb1I3FwM28F1Q5v,iv:eSV7m2stCHWZTDn+BggaXF89yJ3nwUPQYigYZfe4fP8=,tag:2zxb1OGGPvk9Q5/NdC01nQ==,type:str]
    SONARR__POSTGRES__USER: ENC[AES256_GCM,data:sLmVRilk,iv:fJeBfQEMkz7kS0fIoO3ojvJQKk+RtBKQsC+mFGpi2wU=,tag:ZfXaklgqyZhHC8cP2IG6kA==,type:str]
    SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:VjAcLsb/O51r8II41wwsy1m3qi9G+pjt,iv:96aNbnYBDBPAtIFKYMeF1KvZPCyRHMaH+2YbDMpQAMg=,tag:VD1pljYSx+egqvcv9ZPV1A==,type:str]
    SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:5D9AGFgALRzat2Q=,iv:3PXCXiGQClq8yxHpxW0mpMt4UjICUYcx4KwPtxCmsFY=,tag:jetTDnZnojwBO/FOKfAujw==,type:str]
    SONARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:RqiYk+1OBznDIQ==,iv:U91Ew8rkup3D/oNkDEm7SEc3PT8FdxXIuMFHQ8gSqsE=,tag:sVLtjH1hHQyKV3fwmqDvPg==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Fy9CDKJ4QwMxcakpWHtnKUUa8kfPEQ==,iv:JreXCCm7TUc6ywYk1kb4QH8miYdVCGEFBC2LGqEobEs=,tag:TEuYz0Dj4F852uxeVFDC3w==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:Fw81azSWUWJn8FVx5UvKsGRB3Q5s1+af3k7BpiwoBf+/JXSgRzdQ,iv:mKCPiIhxuO2PEONFStRlJ6HSdX4soJNMAzmdHB8vWTQ=,tag:MU/KLr0+RypQIWRJN0vLCQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:6y9W5FiD,iv:8kuqy9W4h5EEThJFm5qTlLTtm0w79/T8959gBbh4XJE=,tag:YAPQmkbTOquoGeILQXBr0A==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:GC6gbdGKrDUzdUhxOEubho6q9nsIm6O5,iv:C2ZP9WrSd8aWBKGyJyGT8WtL3NBAg9xTOOWxOk1wExY=,tag:PYIGP69kmYfxZPCYXwa0Ew==,type:str]
    INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:tRyLvgNCp0c=,iv:6cFxIu0e6UlECMwMgl718iTapI13X2QnfS2NR/7h3Fg=,tag:17/Umdnng08jx0Rr4v1xSg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:RnFKxJI7UCoXbbZ7H6yqlWg5CIClcMJDf50kx01RmbG8LxYPE3iam5GWpxZH1ODZFKTv1lgaJ77FWh/FV/V3bw==,iv:A51ZV5M1YD+6LnrM+CGRmKfzuPoRrW+Z5TJu0zKWpAg=,tag:iQvcTTOIOS7ZdMeo01QRnQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwb0FtSVRUaHFLVlo1MFAw
            T3ZWK1RlQTJ6Si9IQzhtSXRESThVeXIvRGhJCjNUMFNONGpVL0lZVXlCY0lGaWNC
            ZkZqRHlOY1FUYk1RSEhCVzRoem1sSEEKLS0tIFcyVjZMUStqZWx4RFMwZDgxKzFo
            ZkRwTjFMNzZlMWU2Vkcray8vZ1ZPRW8KSE7P8X+0WjmRGkk+yGx+2YpyI2q0BqdZ
            fiOJJs29iuChtFxjUeHdugXDFLf7fY5vKuUTa3TyYerRRj7fso3wtw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hw8r4fnhy55rmvkkrm6lunh5wpmgl6dlam6mhcaxwtm0udvy9u3q78jxgq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T18:49:30Z"
    mac: ENC[AES256_GCM,data:5vltIokbNVPEbj8PKGxvjE9tpJCZhjRImgY9YwJuXQXT3HLezdg+Z/QLBPGBFT68SFHwuGce1xHhOYNMHcXt/doshEwFJ5IL1+JX/Yb69F8q9Af8Ga7MrMUIYffZL8fwjcCcCC/iTfalW7YgcMOb+pzvHrVCjxb7TM7aLUa+0dQ=,iv:ImFnx6pyA11Q8D/YmthdqwGcTQDLU0ytLuGmrzldtfg=,tag:jOjYcfhDf7ajnQRNFGH96Q==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
