apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: security
stringData:
    #ENC[AES256_GCM,data:qucBwA6a/kUMY93aaDY=,iv:RzkKY0qQulvmA3iY33TF+Ci5EM6ou9nKB+VlRnsMiUQ=,tag:vSCqxi2V5HvNl0aApX5HNw==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:hst80EIz4CAE,iv:kHZtP1e4bPNcOA3NQLKTEc1k10zrmpvJ2cxxiXPTKO0=,tag:ugdTTz8AWJ19Y+aRXUdTqQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:+alxp+bFvshS5fd+qgQ8SxwvtR/TpHxVtlTRhYpgm84ph3Bhb07csw==,iv:SP81FT6o8+fy3tMTaATOTY/MvF84DyWKApq3nGuEi7E=,tag:hPH+xZJkoV1XcdR9Mi5K/g==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:fklUZ7+SSsy4BQs0wQ==,iv:eQBgp+iM0OPe41e2zqbPDbp8AmlRN8YA/WiB0HjljjQ=,tag:ny9hT7qB5d4LcbKjGi5XYQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:goHyG6Q4J3IlzFa/C0dTxKvP89s=,iv:FaMJ5C1l8Yvq6nzLCvOV/bHFu2+PA7VzPo5BGqY0XUE=,tag:P2WPKiEALJDTxydDYOR74Q==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:5NJiflSidqClK8pGHTrYmSSd/Q==,iv:g8gPAmRRI/qrUb39NTDITV8X61Bvzh7jfkL7U66oyu0=,tag:Mk3QfYkZk0BKPjtK1cNn9A==,type:str]
    #ENC[AES256_GCM,data:1Y8PovdZc142+A==,iv:t1HKE8LR9SIRunehhiKhjegAB5F6y7D2/ItWk/e7pAs=,tag:Wcj9TwwAFqz9XZFjl2AZQQ==,type:comment]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:tOE7Vxn4rAkD,iv:w3geau8eZqtzIDctUKRqx+aSTLGCei5NeEgxhcNRmLA=,tag:+DtWiTQcztwJl88GsfDh5Q==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:tN6hrXeqrm6sUi0wZ443Df9u2f6/PAJS53w4E4OLzDX0+KMK+wBOpA==,iv:/4/Hh2E2vhLuQyH71w7GpYX7VCsgUJKM47aCNhpxfxo=,tag:TBYaatgLAitv4UwpZxYpqg==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:D9VnimuH6DIRGtQtgg==,iv:X0uRD1K3yw1Ihp98bHMo5225+LtvHJhL1FwDJ5Y1ukc=,tag:YbDnirjc0cAc0y3hhL6Zqw==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:EvwI24yARBnR8yMvWoxJF+AEkHM=,iv:71r3Yf65HCR3uRUTlflK7szkBwoMV4c2JQ0OXxui+hA=,tag:RRqeY9/EB/GRpLp0jXao2w==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:Eg/CBUYR3DnYltQYYfoCa8LX2J9bZjijSqMHf5/7oOg=,iv:EpeYWpplRXeiYDT4vE3Hz+w2QK9edp9kEnfq2oNyQsc=,tag:wxLIA3JiTUUwmlCHbZ2y8Q==,type:str]
    AUTHENTIK_REDIS__DB: ENC[AES256_GCM,data:8A==,iv:Hu/kmRlKYjfaPtJiv72uK2Qi7pLxM2xbP9GJHPXKqpU=,tag:HPvdE/+I3gByHpMKbXUOfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1penp3cgk75mq57r3ytlqgxa53vh2gvvwx2w3q688gpxg4p6v4p7q7jkpdn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZzNFdTN1NXpkWUFadjgy
            WFRZc0V3YmpndDdsL1R3Njk0dk9VMERmSEFJCkMzNStJSkNYQURMYk40eHd0aEJK
            WXBFSlVWZ0FMVi9rVVRpTWtnMXNQUE0KLS0tIFFxTXZhNjBjMjdKMlltTUJZaGlU
            ZUxLdnIyb1VEOTdKL2RiT1ZxbENoeHMKVtHH6gl9Zd+0k1SePcrXlKPfBdUHWrc8
            392+xrbycONygBsBh5zVZjqYAiIMg+hGUrvM+I5JSz17aZMxjHdKAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-05T20:21:56Z"
    mac: ENC[AES256_GCM,data:yatAJV9zrOklJivSQ+9QZAADLvRXa6Cf0qejinwp/tuehl/exYSreoEDtpW9iCvTS7e9z/2EySgNcqAPUfBV4mUotO7oEPBnOQhy8bQvEz7qkeJYyQNW3gdppWg4XBN6QNm7WW2fG35xdiBMSeWva6yv+kwoz7zU2ElRq69Rcq0=,iv:+M9PrqIxF5MeN0b+JMAaFPBn+AY9afKWVRHJqtdMKdo=,tag:An59GxeBOfPsbczo5+6bFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
