apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
  namespace: security
stringData:
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:Bdz4cPnR9/eClpvqmyGuC95/uVlDVFawq/4xOpt2CBuwFvRNDo5XUbhihYRF4T1BV49d7wp1jmFwn6xRMqkivx+G9bFKBNvE+CcyDH0G1f4=,iv:MAlfMAS4DwXaDIhi8ATsZdGiE5OYDUlPV+RZHTGAWzY=,tag:PoMHnActbu7ze45TSLjs0g==,type:str]
  AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:9lcj01JyQs7ydHhzh4ktUuijM84nd0g3JFMpCOUaa/I2uN477e6DXA==,iv:U8wcKsGFySLq5s9CSZOcB5N5AUH9WhpbnAiO+fRTMYQ=,tag:iTmCDjQcVXoAn1IcparSTA==,type:str]
  AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:2ud36x2wMzyoSMIz9UTFmZMdP+Q=,iv:zvv3rHpGlyjMDQ8+RicF1hSwg5UbswWPmqOnl7KjPo8=,tag:Nx8Xcdhn6R1O/4/IiUbDRw==,type:str]
  AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:q8GuQnQ8dbU/8/pnfcVBS/esWN+H24c6+8mpGUt82UY=,iv:st7ArqzRISssvl7vIexx4opPrN27M57vbUrsM8u38hU=,tag:DhllkHpRdPCqt5RPR16zBQ==,type:str]
  AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:cBkLRGD/tyVbXsfKSN52wVdz1QrKiRc1Vgrm4hbNPOuA/bg2qHxrGh7zWft5RQ1f+ohQTfY4MKSTCgTE,iv:myz39xLToZtZHKfUq/rOcJq1cJYgES7mKB7RS6pB54c=,tag:lZkXY3AxgLuEY/u3/rvQOw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUG1TdDR2MUI4MWgxNmhi
        VmtYbzUwZUFzOVBSQlJhMVBUdXlLMjQ5SENvCmFaenE3cHc5U2VEcU9tK2MvR0tq
        QmtYc043T2JFamJiSXd5MHMyVTVZdDAKLS0tIEcrOWl0eEN6WmtHenlXdythSlN2
        UU5OUUp0MW1teEpHNVZvaTFSNmFuVFUKGUW37EcILHqE3Y1BbObUMiyKYYw4MRKA
        WJUKUezWIAAXMVD0bOIfx+gqTmmHXJkxaPAtKiEE1/1mihP1Is+h3g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hw8r4fnhy55rmvkkrm6lunh5wpmgl6dlam6mhcaxwtm0udvy9u3q78jxgq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-29T16:25:28Z"
  mac: ENC[AES256_GCM,data:xpiKKXsTi3CGnQdjsqxp3LzqXcFKiUSjsEYfQdS/MAgJUXlrZL1c8seUuvJU8Y4VODK2zLCGswYz/lv1217s1bL7f0eh5LOw++vWe+b0ap3by4AiL1upO2YpAvXti9lR9IidjBoEIgbOOefQCCD67sC4/UvAX+K2HdmRT2Bt6MU=,iv:mTEJZVfFL5vmRM6mBoRviY3FSp3UhWRPRIC/rciJoZ8=,tag:dxWMqDiFQwP3nZuoWS5GUA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
