apiVersion: v1
kind: Secret
metadata:
  name: authentik-init-db-secret
  namespace: security
stringData:
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:oaqHBSKh31cDx6A3vlTF8xmyyE8KoEUmrpDDEUyuUFH2zZvw4nE9,iv:OIHGTAnnn3N4BWhlQgX/RgqVkBSr23XEBoxrvW8ByrA=,tag:8zmPHLc1ZunK7TXOklFHZw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:v7DSbjMN3LrX,iv:ocqhX2LtIoeRDEwFIgzi/1TdFpTwMODt70PUPqCuzps=,tag:lMMNJagCgiEnDrjsAFWymA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:P5nWGiG0btO9,iv:46Ifr2pIi+64UWTCEN1KSQ6KLko1rrrM+OTXSDK0/TQ=,tag:l2ljyk7MKMaIo4tBXl9XIg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:W29JtKg/kTIMdsOdXBcsBb0lx6Tkokgnk+kKCZvpwm3pAhc3R1+Cjw==,iv:VUTS0ow7W7gfa418Ud3tMUOphPrK8axAiGDyhZmkchQ=,tag:s7rk6Vq9Kee8Gl13FrjL8Q==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:qdh1XcESXuQ=,iv:6LjHf6stQazRDj0h4yeJ+Ek/ZND87b9C6N92b51EMYU=,tag:JMI6/alMxS9lfwWCqcGtKw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:v0i0/EWhjiEyq2OVBtrKydRv9WpwXLeMsP7IEE+4YC3kjCpCRFTXE3FVFC+iaE0t/zpVusjH79NIrBCppu3XPg==,iv:/dqQDSUaE/reGgZpBYs2V0X6WNDhh5/Yewq76dDySGU=,tag:CaKtxhGfI4TmD96tL3oKnA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIa0FvZzFrTzNGTU5XZEtE
        bmZ2ei96Q2lpSVNSbTVmQ21xSFQwaE9IRXkwCkh5eUpoV1BpM3czbEw1NmVWbG0x
        cjBIbmZNTXFXSU9QdExQa3l5UzJmMDQKLS0tIHdlRE1wQllobHBCeFRpQm1ha2Mr
        WGRwSytTT0tpVHBQOFpNNUNZTllYMDgK0Qj5A5D2f6J9XzRapIYxffeDPEikvGJX
        ZaxnXkzOFdpMra992FV2bklW50xGl+gXHd2kalG36AA7IOElrxVzhg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hw8r4fnhy55rmvkkrm6lunh5wpmgl6dlam6mhcaxwtm0udvy9u3q78jxgq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-29T16:25:28Z"
  mac: ENC[AES256_GCM,data:HjBB3BModu1bqag9dk+flgJRIwxFdMErO5KMOxPXzXvthonDwm4nnuewTHJlesQrDO/uCDr1EDZQHCY90AP06Do0rY59oWNe7Ynfpm+o9UYmqBppvXDNqU9hCBdHdvWeweRuwfG6FmZ5kC0fvQD3wnapODsdCuSTH40pGRRmRiA=,iv:7VqNHm0STBoULCE3JZplUDraDmLUD2JqP2Xb/+Iqd1k=,tag:FtLzuGPz7+g/00oXQiul8g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
