#!/usr/bin/env bash
# Regenerate the snmp_exporter config for the TrueNAS NAS from generator.yml.
#
#   ./scripts/truenas-snmp/generate.sh
#
# Writes kubernetes/apps/o11y/snmp-exporter/app/config/snmp.yml. Commit that file
# together with whatever change to generator.yml or mibs/TRUENAS-MIB.txt produced it.
#
# Only TRUENAS-MIB.txt is vendored in this repo — it is the one MIB that changes with
# the TrueNAS release. The IETF/net-snmp MIBs it depends on are downloaded here from
# the same URLs the upstream snmp_exporter generator Makefile uses, so there is no
# reason to carry copies of them in Git.
#
# Runs the generator in a container. Uses docker or podman when one is available,
# otherwise falls back to a throwaway pod on the cluster (kubectl needs to be able to
# reach it, and the pod is deleted on exit either way).
set -euo pipefail

GENERATOR_VERSION="v0.30.1"
IMAGE="docker.io/prom/snmp-generator:${GENERATOR_VERSION}"
NAMESPACE="o11y"

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${here}/../.." && pwd)"
out_file="${repo_root}/kubernetes/apps/o11y/snmp-exporter/app/config/snmp.yml"

staging="$(mktemp -d)"
trap 'rm -rf "${staging}"' EXIT

NET_SNMP_URL="https://raw.githubusercontent.com/net-snmp/net-snmp/v5.9/mibs"
IANA_IFTYPE_URL="https://www.iana.org/assignments/ianaiftype-mib/ianaiftype-mib"

echo ">> Downloading dependency MIBs"
mkdir -p "${staging}/mibs"
for mib in SNMPv2-SMI SNMPv2-TC SNMPv2-CONF SNMPv2-MIB HCNUM-TC IF-MIB IP-MIB \
    HOST-RESOURCES-MIB UCD-SNMP-MIB NET-SNMP-MIB NET-SNMP-TC SNMP-FRAMEWORK-MIB \
    INET-ADDRESS-MIB IPV6-TC; do
  curl -LsS --retry 3 --retry-delay 3 --fail -o "${staging}/mibs/${mib}" "${NET_SNMP_URL}/${mib}.txt"
done
curl -LsS --retry 3 --retry-delay 3 --fail -o "${staging}/mibs/IANAifType-MIB" "${IANA_IFTYPE_URL}"

cp "${here}/mibs/TRUENAS-MIB.txt" "${staging}/mibs/"
cp "${here}/generator.yml" "${staging}/"

runtime=""
for candidate in docker podman; do
  if command -v "${candidate}" >/dev/null 2>&1 && "${candidate}" info >/dev/null 2>&1; then
    runtime="${candidate}"
    break
  fi
done

if [[ -n "${runtime}" ]]; then
  echo ">> Generating with ${runtime}"
  "${runtime}" run --rm \
    -v "${staging}:/work" \
    --entrypoint /bin/generator \
    "${IMAGE}" \
    generate -m /work/mibs -g /work/generator.yml -o /work/snmp.yml
else
  echo ">> No container runtime available; generating in a throwaway pod on the cluster"
  pod="snmp-generator-$$"
  trap 'kubectl -n "${NAMESPACE}" delete pod "${pod}" --ignore-not-found --wait=false >/dev/null 2>&1 || true; rm -rf "${staging}"' EXIT

  kubectl -n "${NAMESPACE}" run "${pod}" \
    --restart=Never --image="${IMAGE}" \
    --command -- /bin/sh -c 'sleep 900' >/dev/null
  kubectl -n "${NAMESPACE}" wait --for=condition=Ready "pod/${pod}" --timeout=120s >/dev/null

  # Streamed tar rather than `kubectl cp`: cp untars into a directory it will not
  # create, and silently hangs instead of failing when /work is missing.
  kubectl -n "${NAMESPACE}" exec "${pod}" -- mkdir -p /work
  tar -C "${staging}" -cf - mibs generator.yml \
    | kubectl -n "${NAMESPACE}" exec -i "${pod}" -- tar -C /work -xf -
  kubectl -n "${NAMESPACE}" exec "${pod}" -- \
    /bin/generator generate -m /work/mibs -g /work/generator.yml -o /work/snmp.yml
  kubectl -n "${NAMESPACE}" exec "${pod}" -- cat /work/snmp.yml >"${staging}/snmp.yml"
fi

# Drop the generated `auths` block. It only ever holds the placeholder community from
# generator.yml, and this file becomes a plain ConfigMap — the real credential is
# defined once, in the sops-encrypted auth.yml the exporter loads alongside it.
yq --inplace 'del(.auths)' "${staging}/snmp.yml"

mkdir -p "$(dirname "${out_file}")"
{
  echo "# Generated by scripts/truenas-snmp/generate.sh — do not edit by hand."
  echo "# Source: scripts/truenas-snmp/generator.yml (snmp_exporter generator ${GENERATOR_VERSION})"
  echo "#"
  echo '# The SNMP credential is deliberately absent: the auths block comes from auth.yml,'
  echo '# which is sops-encrypted and mounted next to this file.'
  cat "${staging}/snmp.yml"
} >"${out_file}"

echo ">> Wrote ${out_file} ($(wc -l <"${out_file}") lines)"
