apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:9pI8G4w5lnXQweGqp3iPoteiAv/biGpVbXAe2GnaULrWWo01LpJS4w==,iv:IJhs4C5zS0aG89JalYsghiQ3Iv4A2fNUlGB7Ba89cmI=,tag:equbGs3ZLmHH+BTO9sO/Uw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1penp3cgk75mq57r3ytlqgxa53vh2gvvwx2w3q688gpxg4p6v4p7q7jkpdn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOW10VWc0RXBtUi9kbFdX
            cVpnUjBJaERRQTdSUUtKTGd3eFluSlduT2pzCmo3QUZqZGRMWTRzb1laZHlMaW5X
            eWZnZHBmUU1QZ2UyZnQ2QVcxZm5jSmMKLS0tIGpLb1JaKzQ0c0VrRzFuYnVPbGpZ
            dkxORDVKYTBQRmxyUCtHVUV2dDZUR0UKNrhO+f1NfWC7frIZ5EUTs52HVTKcRkAp
            sCW330vpYVMthgWOHTjBAHNj8QZxcy6Zpv3hKi3ZLxZwq54E4FZxhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-08T18:10:59Z"
    mac: ENC[AES256_GCM,data:AodlniL5geXUUX1f7ETAfDB22MfcDo3jziJqY3tNY4fNdgGjVuFCTGTpDC+VsdIzmF1osSoPyeLZZxwleXj8QkeuZsgBGYg7pJgjayA+FEJf11OlhiVyWHVLbWpkOiXO56b43BLFsM2vLbpVfl+ogoeCzQbZtR3JjAWqDK3XeA4=,iv:4RzrJpHPlKLfcnlXm7OCweUs4unHsoxcEt2sG6mwqk4=,tag:z0oFQZZ8Z/4Y3C4bByHCBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
