apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:kgZ7bDBLfOa4SaRGXEr82+TPG4t4nzwnzGYDLTKE9XsVT+6H0G2vFA==,iv:yLesYsP8FsT7KgaXW/sEjXsOo3TJpTgkkpHAIw9I7xY=,tag:WRA2cNW4iCIsmDz3dl6u1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1penp3cgk75mq57r3ytlqgxa53vh2gvvwx2w3q688gpxg4p6v4p7q7jkpdn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtc1AwWW1QTW9uU24zQ1lC
            TWY5aGpzeVI3cWdlRWpmTEhocjhZZmN4b25FCmhKQ2NzYkFEOXhWMGNDRlNmMG9i
            OHlqVUd6K1k3Sy9neFVDalV2aFNtRVUKLS0tIG9qZ3lPL1U4d1MyUVZhMVBqbHJo
            RStXckR0UUREanRnSnRpdWtXdXBRaE0K3f52hiJTw9pyoYfUTG4R/4YXDB+/NEUo
            mBnY9yfOQ1lNNsYSTxbNHjR25l4r4n0wwu4owdRt+SRPwJHVuHMMIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-08T19:07:44Z"
    mac: ENC[AES256_GCM,data:jJgvl35mmh3BennWpDlVi2rqNCvNrI8NDzOxGTrDqH5T+h/aIxPOXdOsz0zReokxjSF/Vpwba7QgoDFMbkzsk63trrg6Oh5+lG8ZK7dTAzuvG4o02Z9EF2bOJNdEci5owlmVdmiylny9hzNvnirUNXvX4knEjJiWDEjOIj2/Fe4=,iv:jPD/Lmtftix5SAYBzoUR8ytHFKJ0gtzIKi+ajHWP1f4=,tag:Yyw9z9Cadh0cNgdUZS3x8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
