apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-secret
  namespace: media
stringData:
  PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:OYMB2ywviCbtcsRJUJfVtP/mdPM7CcE2ZB6tRslzajU=,iv:UNmddId7Q6skIhQF4bCb8u58oGZ0xdAQQFWc/ciiC5k=,tag:3yemSI4Rzt2gjNNrR8RFlQ==,type:str]
  PROWLARR__POSTGRES__HOST: ENC[AES256_GCM,data:qcWYpdSsJBPL98Po3YOR7qEv3wzag3rpPX9ijsGboTY4g4aiP7n6,iv:z2WxpAXWQ+Rt1z6o6THWBodTx5YTY92RYlgRogVv2XA=,tag:NxwGD0iGhv/sYf4kWOgOEQ==,type:str]
  PROWLARR__POSTGRES__USER: ENC[AES256_GCM,data:/5nvCee0tsY=,iv:LGq70rANsVJdoaxjHjHtA7flMaqbBmtmKtV0HLz1CuA=,tag:GbMjyCNPj8Gq2M/OsWxxhQ==,type:str]
  PROWLARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:kEz93eNyd1A98bheOqY2kP76pb/vMK8f,iv:zpvx7cnEn0YEl5jh2O22uP69WqIa/Tc31cgyL6WHsK4=,tag:vKVWgR5QN5a7nFUDEpz1UA==,type:str]
  PROWLARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:ObQEenbnWYHT/g7Wkw==,iv:Pp4rameJO1V9C/ZiJFvZd9KodyOKKuELX5bLqoCiQTQ=,tag:/Lo8eyZm6QnDAC5p9dSDbQ==,type:str]
  PROWLARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:F/hb3tkFkIdLcRwf,iv:ldQKDo+7k1TM+j+kMLzTdCWmkuDP5+l/Kfn2mcbV7s8=,tag:Ac8FxY7d+Irjmo/Jv3vsug==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:XLsIfSCc1oUl8dhfsStIsMNpbFTAIbVA5hw=,iv:StCtCkOonmwXmSI4rSkQKQ13s6ho/lgAHppLFOh0iZo=,tag:FtN7EjYhcokivrCDduEsVg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:soGn1o9gJlV+2lUyDJrSNEsZ4mvIgs6/ZKwLY7+fqT8h0mXRV8Dl,iv:Ysg/V6VZ0UgpvIvnLBcXTTmFd/v8nuB8+iL80b9x/3Q=,tag:6Lz3bQwIhFuFCWoeUlQfBg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:wBrpj2Tugu8=,iv:Ynn9z+WKa2onA8MI0xTNkMad+8vrsRs3iuahkD44GMo=,tag:I6Ot1liT2NTfeW+onzW+Tw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Dpx9SeyE+wZIZzFbdPn0OfbG5AGyRwcs,iv:dm1QnBNpMPjtXcu+fE2pAl2NFi/HU0XaYItn2379Jo4=,tag:ql1uGQbVHh25aAwqDaAjdg==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:Ijkiry9ADPE=,iv:46LQlyCb3y8HgyP/U6corVc4zc33QewWeVyrPZs891o=,tag:y9Yyqo58L/pi6EtSB6qWxQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:9isqB7/xXy2pu82GgaxcmQhi12LoWaSftH/f+2+fw87oi4ryvH0xY/nKTOSpYPnknysuA/mq8UmpQEgu0Rm34Q==,iv:4xeKWMpZqcklLOI7N4dlOftS392Dfp4LfB5YOzdI0bY=,tag:1Xls6BXE+Rvmcux/XKxarw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SzZiNUVXVFpxT2g3ellp
        c0wrV3NUWVVnKzR2SWw3dGRGK09iT3EvVlMwCm5tRzB0MkZkWUpSZy9neXVsZDk5
        NU1qTU0vMTBGYitIRTNtR1p3bnkxSzQKLS0tIHZ3VS9Nc1pIa1NkNEFGRXFMVGQ3
        WmlPZFI1SWsyVWFnUC9ra1lmUCtSYmMK6wfo7P5FQsg16xQXoCn+VPCrEJtelK0e
        r4/xYXBZkJjN7FR+lxDvWOeXP7ndZiMKZi5byvvBa6//wD3g55i50Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hw8r4fnhy55rmvkkrm6lunh5wpmgl6dlam6mhcaxwtm0udvy9u3q78jxgq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-29T18:51:55Z"
  mac: ENC[AES256_GCM,data:x1drl4RhejKTigWY34GeSO1iZwTHkWzkZD+95gSBkZTEB5a2OclVFShwTnOFaIDU9cVS26iJkIzqKsz64RdXGT5P3somHpr5mz6vSKXRVK206RYMSN/QtvurD9daBzg3A1qW1NVDMiIjI2JNqWj2dQUprR+gm9q2Lmtg18k3Ups=,iv:SiiLhPPmlmMqory9werWP6jVAcXIJBO40e8yoSscj3U=,tag:kkDgQdENOjkMdmZOn3v4rA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
