apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:w1htHNnQ80u+qYtopF7gDIjVOGTaNfGzXS2kmKWrt1NCVoOvxTG/b4hSllVnqhCX3ORIAVi3VTf5+mZt4NxQ7L9j1IOfUD4sxFDIeEQRQSOE7Y+hUfUtoKsLf89JEheidDL0qOngP11iAIHdaPDCT4yomcRQHYlCpRb0pVfp22cM6TUWcTkdneBB63Uns8ULjZlqZt5E83v7DoOTPA3eAihfioiTRoK1uuMEiMZz0mz0ft7S,iv:/6yF1wfvWHYMsRE1ctXNt4JEGsPynHTHjqVaIXDIqCw=,tag:LlDjbhFbk8yjbm8XHPToWw==,type:str]
sops:
  age:
    - recipient: age1hw8r4fnhy55rmvkkrm6lunh5wpmgl6dlam6mhcaxwtm0udvy9u3q78jxgq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUHdTSWFrMm9YZVZORnRu
        b20vWE90VWhRTmNWYTRFeFpoaDNQbGdiNFd3CnRWZ1c5SkFKNVMvVDdBZkU2UmZR
        SEF5dzhpbWlDbFhTZmJlemRVbENGOWcKLS0tIDVFYUFIdEdMVE5FN1Axa0l1ZTl4
        NVk2NXQ3VTRNNjVNTjhTR1lWRmVvSk0KNxpeqK2dqA9Crs143cqQpAFREiN4I6lh
        tNuJ/yiluqDyhx9rvpSXyhd7YACZHNUlM7aUJjCk8xitzbZPTgw29Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T09:45:19Z"
  mac: ENC[AES256_GCM,data:D3dHkXUuz3mo6PApWUH/UMs7GsThZJrVmJxhNg7PsOeTmTMVkZrH8Nku9nC9H7GXHAgZYRwUv8AXuo9uqw5RL2a9Bxc1y9JLTLwTjDWHwwSdoTNjZHUNRL1xRrpDIqKxCo73Py6nJjHfKRp7Q475yx6mBatu/l+yifApgp294Dw=,iv:DlxyyTHVu+NULeQKXudL1vn4rmTF5+JHEGLPXyc+hsU=,tag:wQ+iq7NhfFEltlSKK6+Ptw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
