---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/onedr0p/radarr-develop
      tag: 4.7.2.7686@sha256:4d60d9dd92593fa2c8bf404d06548b1877ed86d63fa622e5e706c07b7a382e4a
    env:
      TZ: Europe/Stockholm
      RADARR__INSTANCE_NAME: Radarr
      RADARR__PORT: &port 7878
      RADARR__APPLICATION_URL: "https://{{ .Release.Name }}.${SECRET_DOMAIN}"
      RADARR__LOG_LEVEL: info
    service:
      main:
        ports:
          http:
            port: *port
    persistence:
      config:
        enabled: true
        existingClaim: radarr-config
        mountPath: /config
      media:
        enabled: true
        type: nfs
        server: 10.10.10.30
        path: /volume2/media
        mountPath: /media
      downloads:
        enabled: true
        type: nfs
        server: 10.10.10.30
        path: /volume2/media/downloads
        mountPath: /downloads
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: "mdi:filmstrip"
          hajimari.io/appName: "Radarr"
          hajimari.io/group: "Media"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100
    resources:
      requests:
        cpu: 15m
        memory: 298Mi
      limits:
        memory: 515Mi
