apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
    namespace: media
stringData:
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:di77sQbFlbXTLw8j6BJPXQXsWmCiyNrocFbstyEcHHQ=,iv:1qGKRGQ4vp71iDbtINRUlmVQnuJxrPMGj1Uplg0QXx4=,tag:sXRFCq0M4eUb9HcU0HM2cQ==,type:str]
    RADARR__POSTGRES__HOST: ENC[AES256_GCM,data:LMPCkkcKjDF5jZ6DWdYBmqe6XKsnpIOqkejFqn184od4OQ6VBopr,iv:C5atDFDrx6cWBGV6S0Ihn/MV2IxXCS2Z4T4fQx7PTQk=,tag:CUdoj1JZadbD1X+szrA6Uw==,type:str]
    RADARR__POSTGRES__USER: ENC[AES256_GCM,data:ASGC5cIj,iv:Djs1vHUK/8bS5p+zlDhlPVNOvfw2JB2L6wA4q8IYXrM=,tag:2X7ZYOCQliZOKf5QxXPGTg==,type:str]
    RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:bLchhKEqxxePdbNMmZFWR2aFwUB6d+RX,iv:kpEBBmZ5IZfeGGm81OYDWvUwI1qkaULN6mvdy9qXBV4=,tag:sq8sSRVR6nH5Qsr7JxYRtA==,type:str]
    RADARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:es/WnPnspsbGWPw=,iv:/JlmuvB41YKkfgdCzsxcwylMo34zwm11arXIhEvmWe8=,tag:Cekzdd/y3EAxfBXrAeVdEQ==,type:str]
    RADARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:hRnBIio+KiOUzA==,iv:WskurVlVs1qBTbNYbJJB+3Id72PM+zSPdbLpx7T2sI0=,tag:KUXoaQnC7GkzDMpG8ReU+A==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:NOWfFBtm8iNsh+p/UDAN7RBfNF/5Mw==,iv:4fbGWIn4q4pgC8fd7f853LbQcdpbfi74HxEPVvZBMbA=,tag:M/BeNwPIDqCF2jZxqtplIg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:nrZXBMEQ2TusHT7zFMuEt64IXGuZMCd4R+v26CVaKmscnSMQNNFQ,iv:wKtcyh8ZvyRxf7Sx586lfoAKBeD7CPbkwu0KCnow5Io=,tag:MnZ6kP8zkJC4w0NiEWBh/Q==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:+XR3+xTx,iv:l676Wg4RVzJEVa2F2HIykDEcpUAGrUpN/8g0PFAcuAY=,tag:rfK1Lu87Upj+nZtqFKvXLg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ZzqKESnCY58wu5Z2v5nN1LmnwW1clcyS,iv:Ot/zgzmYtamW1GC0Eh/nuBPDh3cokgISOIJxBdjLE0M=,tag:1qQsUJnPVzzZVIm+laQQQQ==,type:str]
    INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:hI0U4/KJvSQ=,iv:8PGEoSQ/7vpllP6xulNR27SGVj1zxPj3WfDtj95GyA0=,tag:0t598jpJR7ta4ljbYjjRYQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:8TyMo3ZEKwlbaBlzDX+obONvp14uOrQY18lsdtuNolJDRkENbvzOJfJ+9GO7Un7pzGxBe8dBYFt+YHA0V0CwhA==,iv:dLgtCfmoZhm37hrOwfgIoRVoEkFRNFItPFkP/wY6e/c=,tag:PG//kzJarW62PZNBzR2kEw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucDdlMDNOd3JwbXJiWU1l
            c1VoYVRSbEp6MGtQOUhiQWVLK0lLVmFUUmdNCnA4eHZJRlphTDRoa2pTMEFFbHVG
            VDVSWElZS2YrNHZVOHpidE1jSDl4MDAKLS0tIEZTWVRNVUwyaUtwSFR2VVRBZ3BG
            clMzNkR2bnpaaHlnNFN4SkU0bXh1d1EKZi1FbzPxGIoRfPNbRFZr/YpxMAI8bcXi
            A9v25sZ7wrmE1kzcA8O/GRZ+O9P0fB4lhusef2+4jZ8RwE/ea4PNAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hw8r4fnhy55rmvkkrm6lunh5wpmgl6dlam6mhcaxwtm0udvy9u3q78jxgq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T18:50:27Z"
    mac: ENC[AES256_GCM,data:+WzIUNvUp5as7DbPVrC1Q6nYx5ny0+W/3wQfCvfvYj+r2ndI84O8HlbazlLpW9v2ZSlPU84r3vN4i8c6KliQmkAtzPGQqUWF4MkyZJSEL2wdkgPBGnFhVSx3BPwjjvVwndZRg+6VoxVHbwE6er4jAblK1d8iIp17+YjhFxsiTRE=,iv:d+VU71enJdnvngIGzRyHiZQ6mBFdYwxM7dmQ+zTqofU=,tag:/JIYQ/KSjcnhAJvFcXNuAw==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
