---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pod-gateway
  namespace: vpn
spec:
  interval: 30m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system

  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.11.1@sha256:0617304f085bc98529f0c5cd0c40c63bb019380a026a277c812bd13f78b4bc5d
#    DNS: 172.16.1.1

    addons:
      vpn:
        enabled: true
        type: gluetun
        image:
          # TODO: Replace with ghcr.io/qdm12/gluetun when a versioned tag is available
          repository: docker.io/qmcgaw/gluetun
          tag: v3.36.0@sha256:011bea4f0743864d4eda5a569217a6fe18e3a52f5d6df31b4ceb9f7763bfbf6b
        env:
          - name: VPN_SERVICE_PROVIDER
            value: mullvad
          - name: VPN_TYPE
            value: wireguard
          - name: VPN_INTERFACE
            value: wg0
          - name: FIREWALL
            value: "off"
          - name: DOT
            value: "off"
          - name: SERVER_CITIES
            value: Amsterdam
          - name: SERVER_HOSTNAMES
            value: nl5-wireguard
          - name: WIREGUARD_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: pod-gateway-vpnconfig
                key: WIREGUARD_PRIVATE_KEY
          - name: WIREGUARD_ADDRESSES
            valueFrom:
              secretKeyRef:
                name: pod-gateway-vpnconfig
                key: WIREGUARD_ADDRESSES
        securityContext:
          capabilities:
            add:
              - NET_ADMIN

      netshoot:
        enabled: true

    podAnnotations:
      secret.reloader.stakater.com/reload: pod-gateway-vpnconfig

    publicPorts:
      - IP: 10
        hostname: qbittorrent
        ports:
          - port: 56202
            type: udp
          - port: 56202
            type: tcp

    routed_namespaces:
      - downloads

    settings:
      NOT_ROUTED_TO_GATEWAY_CIDRS: 10.0.0.0/8 192.168.0.0/16
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_INTERFACE: wg0
      VPN_LOCAL_CIDRS: 10.0.0.0/8 192.168.0.0/16
      VPN_TRAFFIC_PORT: "51820"
      VXLAN_ID: 43
      VXLAN_IP_NETWORK: 172.16.1

    webhook:
      gatewayAnnotation: setGateway
      gatewayDefault: false
      gatewayLabel: setGateway
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.9.0@sha256:4e169da5af107a9c6c784d3e03c89da07fad45f18358ab5b7177662df12d955a
