---
## yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vpn
resources:
  - ./helmrelease.yaml
  - ./pod-gateway-vpnconfig.sops.yaml
  - ./networkpolicy.yaml
commonLabels:
  app.kubernetes.io/name: pod-gateway
  app.kubernetes.io/instance: pod-gateway
