apiVersion: v1
kind: Secret
metadata:
  name: whiteboard-secret
  namespace: home
stringData:
  JWT_SECRET_KEY: ENC[AES256_GCM,data:S/zyoRYWLe0gDrXjPIte3JQmevrPoO/BpkiosnuQ+ombt+9PmJtCNu3Juf6eyZ1A0unAVEHlejJFfT0R4YUrxA==,iv:n71jfwhd/vyz2STlB+iPA9tCql4+PASUWeonsgvRkTE=,tag:S2IqqT77CgMdY1ORLs5FTA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbUIra3NHRUJhV3NJZUE0
        N0RqbTNQZHNKTFlJTysrZDRNQkJ4K3kwcjJVCkt0dzMxY3MwMGJWeFMxUnJ2MENp
        SXp3WG5TeGpMSWZvVDNOZm9HQ0Y5bmMKLS0tIFJaQ3A0MUhWTXBWTy9TYzk0WmtE
        WkNJaExMRjZ2eE5rMTJuWmZpdnZnSU0KUAwE5tTYZLDC4Q2NSdk+wAKIeaLFrLol
        5MrpIC9l0JMOHncfYCyFQZSUryXQfCGQ2MsEE+EC+ykUzDhXyreSdg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hw8r4fnhy55rmvkkrm6lunh5wpmgl6dlam6mhcaxwtm0udvy9u3q78jxgq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T22:12:29Z"
  mac: ENC[AES256_GCM,data:e7WEpcZ1xsHrlbyg9E1Ulif0b3aR4/Zbl/loawMxp/MFHK2CiWKWNTOzDGWpYGfo5EU4+H5c+Pi1Q0EXR6bospPnSNE3mARIIq+dfjwSMYu4fQaQZPeAeP/F7DJnmXuno1WQAYAjOxmzh3oKsUWNZapCqy8ZNVMQurTF32KVNcA=,iv:VBbK+IUbVfI0gNo6pWHK9XGRYzZ3S+SmfGDapZa3C8I=,tag:wCr3gAkrV4Em7lCJLqLlbQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
