apiVersion: v1
kind: Secret
metadata:
    name: unifi-dns-secret
stringData:
    api-key: ENC[AES256_GCM,data:pddDOHSNk4o1i+ih974wmss9UBXVgNTym3Theyp8Lps=,iv:FESVA1xirHOOUOigPMFbZVadWbcjQgHtXdUBc7cnjAQ=,tag:+fihq7rXj6Sbq3SMwA3uPg==,type:str]
sops:
    age:
        - recipient: age1hw8r4fnhy55rmvkkrm6lunh5wpmgl6dlam6mhcaxwtm0udvy9u3q78jxgq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNVlQdUhodXpWaEVMbGhs
            U2dVbmNod095NEE2c3NoZzZoNjR6aUZMQVdjClNLZDBoRVNCdXQ1VWV0cE55ZXFK
            eHJMNzlyd3NzTzZJSDZNbG9vTHVUTVkKLS0tIG0rV3JjKzNwSWdqenN0ZGVJa1pU
            VGlyRFZwZisrc1o2SVppWGpMbWZFQm8K7m0RvEHzeQR+4wvFwCSdiqFzGZ036Cgc
            u/v0Az0UmrbVc+y2unolvk6XnMqY7UVSOtddWcCYs9g9CbhuTQCEog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T17:31:59Z"
    mac: ENC[AES256_GCM,data:H3hf6mPz/kDb4AyNW/Lfd2j3EteDfV5QEA16QQgAD3br2VZ3gzbpgimdKBJggrieqYNl89aOTF4JJpZOMhJpwpujgPGmAu62nbuEM2IkcMCBSUzomtoXIvPolu/BjF/IqX25HAkedVRNTI2XEM4OYggAd10cunRyh6ZJmaEjJhE=,iv:D+cojiFqSxb0txVzhwrheiDGm3ffiEoYu6XSYKHS414=,tag:1jbGj8WQOV2rQDn1mg6qNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
