---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: databases
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: redis-authentik-haproxy-configmap
    files:
      - authentik-haproxy.cfg=authentik-haproxy.cfg
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
