---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opensearch-operator
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: opensearch-operator
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: opensearch-operator
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    installCRDs: true
    serviceAccount:
      create: true
    securityContext:
      runAsNonRoot: true
    manager:
      image:
        repository: public.ecr.aws/opsterio/opensearch-operator
        ## tag default uses appVersion from Chart.yaml, to override specify tag tag: "v1.1"
        tag: "2.4.0"
        pullPolicy: "Always"
      # Set this to false to disable the experimental parallel recovery in case you are experiencing problems
      parallelRecoveryEnabled: true
      dnsBase: cluster.local
      # Log level of the operator. Possible values: debug, info, warn, error
      loglevel: info
      securityContext:
        allowPrivilegeEscalation: false
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 350Mi
    kubeRbacProxy:
      enable: true
      image:
        repository: "gcr.io/kubebuilder/kube-rbac-proxy"
        tag: "v0.12.0"
      securityContext:
        # allowPrivilegeEscalation: false
      resources:
        limits:
          cpu: 50m
          memory: 50Mi
        requests:
          cpu: 25m
          memory: 25Mi
