{
 "title": "TrueNAS",
 "description": "TrueNAS grafana dashboard based on prometheus + snmp-exporter",
 "tags": [
  "prometheus",
  "snmp",
  "truenas"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "host", "query": "172.16.32.10" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(hddTempValue{target=~\"$host\"},instance)"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "label_values(ifHCOutOctets{instance=\"$instance\"},ifName)"
    }
   },
   {
    "name": "datasets",
    "label": "Dataset",
    "query": {
     "query": "label_values(hrStorageAllocationUnits{instance=\"$instance\"},hrStorageDescr)"
    }
   },
   {
    "name": "pool",
    "query": {
     "query": "label_values(zpoolHealthStatus, zpoolName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance=\"$instance\"} / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Used",
   "type": "gauge",
   "gridPos": { "h": 15, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "datasetUsedBytes{instance=\"$instance\",datasetDescr!~\".+/.+\"} / (datasetUsedBytes{instance=\"$instance\",datasetDescr!~\".+/.+\"} + datasetAvailableBytes{instance=\"$instance\",datasetDescr!~\".+/.+\"})",
     "legendFormat": "{{datasetDescr}}"
    }
   ]
  },
  {
   "title": "Disk temperature",
   "type": "gauge",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hddTempValue{instance=\"$instance\"} / 1000",
     "legendFormat": "{{hddTempDevice}}"
    }
   ]
  },
  {
   "title": "Traffic: $interface",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (ifName) (rate(ifHCInOctets{instance=~'$instance',ifName=~'$interface'}[$__rate_interval])*8)",
     "legendFormat": "Traffic In"
    },
    {
     "expr": " sum without (ifName) (rate(ifHCOutOctets{instance=~'$instance',ifName=~'$interface'}[$__rate_interval])*8)",
     "legendFormat": "Traffic Out"
    }
   ]
  },
  {
   "title": "CPU used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssCpuUser{instance=\"$instance\"} + ssCpuSystem{instance=\"$instance\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Physical Memory Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(memTotalReal{instance=~'$instance'} - memAvailReal{instance=~'$instance'}) / memTotalReal{instance=~'$instance'}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "ARC hit ratio",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zfsArcCacheHitRatioPercent{instance=\"$instance\"}",
     "legendFormat": "Arc"
    }
   ]
  },
  {
   "title": "L2ARC hit ratio",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * rate(zfsL2ArcHits{instance=\"$instance\"}[$__rate_interval]) / clamp_min(rate(zfsL2ArcHits{instance=\"$instance\"}[$__rate_interval]) + rate(zfsL2ArcMisses{instance=\"$instance\"}[$__rate_interval]), 1)",
     "legendFormat": "Arc"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ssCpuUser{instance=\"$instance\"} + ssCpuSystem{instance=\"$instance\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Physical Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "memTotalReal{instance=~'$instance'} ",
     "legendFormat": "Size"
    },
    {
     "expr": "memTotalReal{instance=~'$instance'} - (memShared{instance=~'$instance'} + memCached{instance=~'$instance'} + memBuffer{instance=~'$instance'} + memAvailReal{instance=~'$instance'})",
     "legendFormat": "Reserved"
    },
    {
     "expr": "memBuffer{instance=~'$instance'}",
     "legendFormat": "Buffer"
    },
    {
     "expr": "memCached{instance=~'$instance'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "memShared{instance=~'$instance'}",
     "legendFormat": "Shared"
    },
    {
     "expr": "memAvailReal{instance=~'$instance'}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "hddTempValue{instance=\"$instance\"} / 1000",
     "legendFormat": "{{hddTempDevice}}"
    }
   ]
  },
  {
   "title": "Dataset Used Space",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "hrStorageUsed{instance=\"$instance\", hrStorageDescr=~\"${datasets:pipe}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hrStorageAllocationUnits{instance=\"$instance\", hrStorageDescr=~\"${datasets:pipe}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Storage / ${pool}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 }, "repeat": "pool" },
  {
   "title": "Pool status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zpoolHealthStatus{instance=\"$instance\",zpoolName=\"$pool\"}",
     "legendFormat": "{{zpoolName}}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "table",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "datasetUsedBytes{instance=\"$instance\", datasetDescr=\"$pool\"}",
     "legendFormat": "{{datasetDescr}}"
    },
    {
     "expr": "datasetUsedBytes{instance=\"$instance\", datasetDescr=\"$pool\"} + datasetAvailableBytes{instance=\"$instance\", datasetDescr=\"$pool\"}",
     "legendFormat": "{{datasetDescr}}"
    }
   ]
  },
  {
   "title": "Used / Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "datasetUsedBytes{instance=\"$instance\", datasetDescr=\"$pool\"}",
     "legendFormat": "{{datasetDescr}}"
    },
    {
     "expr": "datasetAvailableBytes{instance=\"$instance\", datasetDescr=\"$pool\"}+datasetUsedBytes{instance=\"$instance\", datasetDescr=\"$pool\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Pool I/O (ops)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 52 },
   "targets": [
    {
     "expr": "rate(zpoolReadOps{instance=\"$instance\",zpoolName=\"$pool\"}[$__rate_interval])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(zpoolWriteOps{instance=\"$instance\",zpoolName=\"$pool\"}[$__rate_interval])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Pool I/O (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(zpoolReadBytes{instance=\"$instance\",zpoolName=\"$pool\"}[$__rate_interval])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(zpoolWriteBytes{instance=\"$instance\",zpoolName=\"$pool\"}[$__rate_interval])",
     "legendFormat": "Write"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "ARC Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zfsArcSize{instance=\"$instance\"}*1000",
     "legendFormat": "ARC"
    },
    {
     "expr": "zfsL2ArcSize{instance=\"$instance\"}*1000",
     "legendFormat": "L2"
    }
   ]
  },
  {
   "title": "ARC Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 90 },
   "targets": [
    {
     "expr": "zfsArcCacheHitRatioPercent{instance=\"$instance\"}",
     "legendFormat": "ARC"
    },
    {
     "expr": "100 * rate(zfsL2ArcHits{instance=\"$instance\"}[$__rate_interval]) / clamp_min(rate(zfsL2ArcHits{instance=\"$instance\"}[$__rate_interval]) + rate(zfsL2ArcMisses{instance=\"$instance\"}[$__rate_interval]), 1)",
     "legendFormat": "L2"
    }
   ]
  },
  {
   "title": "ARC Hits / Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 90 },
   "targets": [
    {
     "expr": "rate(zfsArcHits{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "hits"
    },
    {
     "expr": "rate(zfsArcMisses{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "misses"
    }
   ]
  },
  { "title": "Networking - $interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 }, "repeat": "interface" },
  {
   "title": "Network Interfaces",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "ifPhysAddress{instance=~'$instance',ifName=~'$interface'}"
    },
    {
     "expr": "ifAdminStatus{instance=~'$instance',ifName=~'$interface'}"
    },
    {
     "expr": "ifSpeed{instance=~'$instance',ifName=~'$interface'}"
    },
    {
     "expr": "ifOperStatus{instance=~'$instance',ifName=~'$interface'}"
    },
    {
     "expr": "ifMtu{instance=~'$instance',ifName=~'$interface'}"
    }
   ]
  },
  {
   "title": "Interface Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{instance='$instance',ifName='$interface'}[$__rate_interval])*8",
     "legendFormat": "{{device}} in"
    },
    {
     "expr": "rate(ifHCOutOctets{instance='$instance',ifName='$interface'}[$__rate_interval])*8",
     "legendFormat": "{{device}} out"
    }
   ]
  }
 ]
}