---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unpoller
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: kube-prometheus-stack
      namespace: observability
  values:
    controllers:
      unpoller:
        containers:
          app:
            image:
              repository: ghcr.io/unpoller/unpoller
              tag: v2.15.3@sha256:56069bd90291a7c63e58b594e877c5f868a58f082e20c4c533e4e546ed3b42b3
            env:
              TZ: Europe/Stockholm
              UP_UNIFI_DEFAULT_ROLE: home-ops
              UP_INFLUXDB_DISABLE: true
              UP_PROMETHEUS_HTTP_LISTEN: 0.0.0.0:80
              UP_UNIFI_DEFAULT_VERIFY_SSL: false
              UP_UNIFI_DEFAULT_SAVE_ALARMS: true
              UP_UNIFI_DEFAULT_SAVE_ANOMALIES: true
              UP_UNIFI_DEFAULT_SAVE_DPI: true
              UP_UNIFI_DEFAULT_SAVE_EVENTS: true
              UP_UNIFI_DEFAULT_SAVE_IDS: true
              UP_UNIFI_DEFAULT_SAVE_SITES: true
            envFrom:
              - secretRef:
                  name: unpoller-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: unpoller
        ports:
          http:
            port: 80
    serviceMonitor:
      app:
        serviceName: unpoller
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 30s # Unifi API only polls at 2m intervals
            scrapeTimeout: 10s
