---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matomo-pvc
  namespace: web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
