---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Stockholm"
  KUBE_VIP_ADDR: "10.10.10.40"
  METALLB_LB_RANGE: "10.10.10.210-10.10.10.230"
  METALLB_K8S_GATEWAY_ADDR: "10.10.10.230"
  METALLB_INGRESS_ADDR: "10.10.10.210"
