apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:CN1c1D2ckEs4Oi4VzmM=,iv:1/OW5BbKW/7FveIa70tBKnq8vEMlSCE7c2szMPa2OI4=,tag:8aVx9oeXtUlrXhglj98pQw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:c3boxf/BdhtL1CNdQKBCjU9vAbVU1CveBg==,iv:g3/Cw4WsQNiGiwFfYtItOycdhieqciy1POsikxykAe8=,tag:ILc1BQjrbxd6S9RgSBNfWA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:doMJGsMH+E+NyidOFTpTZzWpWbdwFwxqXZOd3gNkrzkteVpV,iv:MqVlxYOYPZeLD36kNANsK3HJl6ubp4kfZ085BuAveGQ=,tag:YGy+Wf/iNI+Cg+PE4PrHBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1penp3cgk75mq57r3ytlqgxa53vh2gvvwx2w3q688gpxg4p6v4p7q7jkpdn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSHF1dkVsMUM3WDg0V0Nt
            Y1gvSXZwU1VkcUoya2g2UjVRN0tyY1pMeW5BCjZFSTI3bmJJMTJjcTBJZ0hCR1Vw
            WWorNUU1SGxjY3lDRnlCcVQxaGtqTDgKLS0tIG81REZocFZzNlhHOEdNbU1TaDBO
            cHRzMGcvYW5DZXdGeGN2WFFoMUh2L1EKK3bMFqcQQyRvXVqQBxZ0h35v+nbqJEXB
            Di5KcM31me3Gr0TEprld35Sbw7KWTZ8v3ETs1wdzCnQOrFHp77fJwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-08T19:07:44Z"
    mac: ENC[AES256_GCM,data:8dv7vHA/SYTNin2ubi7ak+mgqRfZca1tXmHheBWzzryvpLDxnp05SsCdxIdHfsWhHIlE9kfGIiWAqnjWq52EpsOm6xhPOL3Q9v8XfcV7vZ9NzCQDAKvUr8dYWOE07dwMwKpyxhyTchbdCCvjk5lz9kccHyIfp2E5VX0yumgdbCE=,iv:i88LApK8tJYTICOB8dycHLC7ERrD8OFz9MqPRbxNN7M=,tag:x8bosHPAqsPBI3lNW617mg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
