---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-claim
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ceph-block
