apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secrets
    namespace: database
data:
    email: ENC[AES256_GCM,data:kXue4pPQtpVD6ronrC+fCnU7BAxpyxJnPY7wn74SHbWhLcSY,iv:gXTIzKqBimxWwTH10eDFHY4yyUvPw4z29w08FXSiK/Q=,tag:niLCHm31A+/dya/akFygfA==,type:str]
    password: ENC[AES256_GCM,data:K/PEU6+DJ74TBaky7gVXwRAuVExvFsoSRysS6A==,iv:KKKoW+XTAJTAE94Ffa8fOUFry1s9LcHILkL7LVI/b6Q=,tag:N1dzx9XXFlPdpR7igiJRWQ==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:PkScdM2iCzmKWuQrTIG+8I1XrEngS9p9v/PaDA==,iv:BjnJHw1GhRtow2SAbmtF2HtXD4kEvdHHRLZoWryhMiA=,tag:tC3wqctEIQhRd7e1tkpCMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1penp3cgk75mq57r3ytlqgxa53vh2gvvwx2w3q688gpxg4p6v4p7q7jkpdn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTmRiOFlWRURuOHNIdkFL
            R0g1UTRQc2ZFeGNoOXgzdDg1NWhLNEM4VVdNCmUzUjUvajFaRjZLdEV5aWRrdEJN
            VHJJRStSM1VoL0Rxdm1hY2ZERjVzOEkKLS0tIFpQRUxzRzRPMW9vNEsyTVFyb0Vi
            MGdzQ2RRMUVLeWhRRlJWOWpaaGJQT2sKSCPJLfV1F8eWJNw/RhsDF6WaZ0WYFvlL
            tyiGvQqkWeFB5+3O6fqrTBRHauNYO35ZEBtlVA8YttkxTAMJOnCeyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-05T21:01:59Z"
    mac: ENC[AES256_GCM,data:091i/ffnsRgdUfk4tYq0QZRoNSLohl0XlY7bYInTd8Btyc7mQXuqAZR5jCtNRaS7Es8pln6mAl+iU3H0yKIMchdifA3kfJUm/GpM3P6peAStZvfxEehsFSPgkegMa3Ukpg0ixTCwO+asfn9kU2qtjRxW7FxxR8KbnAhE7sPumAE=,iv:q9xjrM/femxNvjvvVkQidvIhCTz2uc1BgMT6xT0f7bA=,tag:woXF7P360EciIPDc+3ChoQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
