---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: databases
spec:
  interval: 15m
  chart:
    spec:
      chart: mariadb
      version: 16.5.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: bitnami/mariadb
      tag: 11.2.3
    auth:
      existingSecret: mariadb-secret
    primary:
      persistence:
        enabled: true
        existingClaim: mariadb-pvc
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
