apiVersion: v1
kind: Secret
metadata:
    name: mariadb-secret
    namespace: databases
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:XsbpeSJOOWZsdit6sSfN1wJ4k9+4hAqdHhw5i6sQBt8=,iv:xS1LJQyb00jLnw6g8yuBLb047OBraiwgJ1vAkSBxD/I=,tag:1L68ZbQZw6kwuhAWU8hDwA==,type:str]
    mariadb-password: ENC[AES256_GCM,data:vglMr0x88XIBeCJySuJU6nSee5TxtJ8b9v5VFbs23EE=,iv:VgwMwc3+CmJDvnGcaqgHznHsb0XMhVTZ+9zNaOdSEdc=,tag:nv0LXEUAJ31PmS4zVP0mbw==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:MZdIMHdpozV7RywP2bvIelLaVhEhaXb0LHJYOtcr2KE=,iv:LFJuDm5yVIlR3VkKwINltu1YrWQziFqwKP4qEO2kXy0=,tag:pyq/pwiJ2pZ+lxSreaqcCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y6admte6g24crgupz4lpaszp0vxr9nntyjprjk27trp9ustvzumsml44sg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXN3ZpM1NSZDNXckNybUJC
            N3NreHJXOHc5cnRSbDdUUnBsQmJIQUxNeG5BClpzUjNVUEl2YWhUY0R3NFVOcDZ0
            NjhXMUE2Tk1PYlM2NjdGaUZuZ0pFdzQKLS0tIHMxYkZMYVdhQUp1OGtibFFJa0ww
            blMrVm9zbHBON0diVHFyTXBCQVppVW8KuTzBn0K7aeuNZPr7qh4mk3HEtPN9IL6u
            cBxfrkKXuffgEqWCRg65/kEDNRBqGHAPg3N3xTTHCWZLOpxfWjEnKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-27T17:54:14Z"
    mac: ENC[AES256_GCM,data:jFKPCYeDJ/iHQc0GYff44TbjwrlP5/LPOCiKquCU2/eN9J9dXWF23hkpNgvpO4BPxQAxQl4OaadiXO/0/dVmpenE7C2jKv75L3Q/g8oJaIgSSOLhqT+M0dmZ2Ncbar+8L7m8s0fcAE1PkkgMq7Lkh30SWWpWDmker2v2MMku2cQ=,iv:BmHuJNpxvGpyIBtsZqZmNjIZbSBTTwH5PLyalfRr19E=,tag:g1S5PHwVttv3g/qbu+eA0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
