---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-nextcloud
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cloudnative-pg
    - name: cluster-apps-cloudnative-pg-cluster
    - name: cluster-apps-nextcloud-redis
    - name: cluster-apps-nextcloud-redis-haproxy
    - name: cluster-apps-rook-ceph-cluster
  path: ./kubernetes/apps/home/nextcloud/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: nextcloud
      namespace: home
  interval: 30m
  retryInterval: 1m
  timeout: 3m
