---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./grafana.yaml
  - ./grafanadashboard.yaml
  - ./grafanadatasource.yaml
  - ./secret.sops.yaml
  - ./secret-oidc.sops.yaml
  - ./servicemonitor.yaml
