apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:YdOwwnU8vhgQjE0KgJYbqDxbfaW4wXV1olVd5np/h9c=,iv:XfbpQWNUQPjLvQNJyY6R8mVtGfRYRDjQhmBpfQi1cFc=,tag:U8Ri3IFGo/AAqexWmn2XbQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdWRvNEY3d0ZaZmh3cWMx
        NENOdERkenphOFk0eW1PT0tkb21kLy85b1hvCmZSaVhML2ZvMFBpenV3UjlKb0Qw
        U0FKSC9hSFg4YlNVK1FrdnpWbXRlRU0KLS0tIFNsUEYwUmQ2K1MxNGFudklQV0pV
        bnR2WG83L1ZSdVoxTG9ac01XRmh4Y2MKngvyLK5fLUAcSeOb22pGjjc82bauKqsy
        E7z+hPEwXSZE/oktNueod0Jwwr4zDW/CrMF0ADaG4LvzTMEohJRkwg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hw8r4fnhy55rmvkkrm6lunh5wpmgl6dlam6mhcaxwtm0udvy9u3q78jxgq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-09T19:43:49Z"
  mac: ENC[AES256_GCM,data:2AqkAhaCglut++46DXa2KmhcPSw7M2vXbgnTZglxQab/1pGMkF7ApRw5sYGZPoAmrje2ezV47EO2VsWhe2iEArN4B/Rim9u58QgaKrKsoB7bgzyiuIL1277i9R7HjR2HJzkgR3r4ZB+Mn7Av3Em6+yIRofO873/TcbfMOeoRAoo=,iv:mRO1wtrfZzOqQ8PpRz/23hxMEkyjck8PN3M/WX9JYwU=,tag:NBqtdFEcM7TjsD3jnhpZdw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
