apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:zKZUdTn7eP8hypGp20LC3OJLo20s9QXqLqh8SgBIzgKIgreEQQ+IOQ==,iv:sShHtlSoDNTyzSxpOsRfXqj6cgisn/zvCD+V30QJ1z8=,tag:QQoklBkTz+TRVymFMowGMA==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:N13cUZ8TgYOR6t0qZ6dFcKnrny4ipcXG98anXcfCQb+grbyOGoWlfkV8KkXP4ZhJGU0euEMHnT6gfhooqBdkAf8ZP/JZgObvn6tdE8X3iuk55lXxfibnTYG3/NZUa49gmLb10fvRC4N/4yIA3LuSru9PRh5Xbsztvd7jsH+w3eY=,iv:NtAXEF0oYJ9buTDwN+mIAssy76FjWkDJ/6VRNWoxrQQ=,tag:lixgrP/L6/ZA0B9+DLQo5A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRHl1YWdLQXhlUlVCTnE0
            U0tyallhdGttUUlNTkJ6NXdFYlNBTEdUL2lRCi9SZ1QxYWUwK3ZqZ3U2eVMzYUVh
            QjB4MGNtYzBQMXAwajJMTFpJMXJGdEUKLS0tIDl0bSt3bjErWnhEVEZRU044ZTU4
            MUN0V3lBYXFIbUZwR1o1RG5lRDBVN1UK9iKZBXi1/1nnIrHPHOYaignYFXpx1L8w
            mkRM9TCd5KogRlwghHyqNTBIsPGphotFyYgMVKEWS69pH8Dp5tqu2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hw8r4fnhy55rmvkkrm6lunh5wpmgl6dlam6mhcaxwtm0udvy9u3q78jxgq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T21:20:55Z"
    mac: ENC[AES256_GCM,data:44R8wUfR2bCQLvzGOklFpdihAvfUBZKwtwHZ3P3LXqrrfnd554OaQkQhxDsXGtiwEoXsZH//yqf5jl1rj8MoV/wt3gIBysYM9NoWqM+WI2HjoXSMxBhHTwfuIgakrF8AyYb84xCXSZEAmlpoKtZP6YflHqtX8V+lFeVHBa9sQzU=,iv:uIEkQvGZpeNilMBiAqHgYezVIYKYODUf/DqAz7ta9x8=,tag:rmeBA2jpnBV94r/B2b7NaA==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
