apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:67KI7Uzk1CYpUMI0V7fefxUOqxMMiR8xoH3GSixvqQm/acMtilabHw==,iv:yGdjigq1h9wNPcesOVKrXLCiXbBFApfcxv6x7vPDm1Y=,tag:Qk6ZBf4VaKSebgBl9YDjGQ==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:CuDp1qPH2xVWK2JraXrH68eSqTBwYEGffHNdPy2ZLdlRTKabN2/ZjymZGlayDjL8ZmWYEGjlIjF4vsF5XGK9s74SGrgmLB+qKFqCwHRR4KOSBdj2kha3jp4vkhGH/DsyYJU+IecDm9OIzIQVaqYNGuqjNBCotppsGuC+ddAB3KI=,iv:2Pm1vh+5/HotGESdhX/oZcaC3fcKLkRNn6DWdfXfc1s=,tag:Cn3+KGSeXApr5vgIMprQtg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRHl1YWdLQXhlUlVCTnE0
            U0tyallhdGttUUlNTkJ6NXdFYlNBTEdUL2lRCi9SZ1QxYWUwK3ZqZ3U2eVMzYUVh
            QjB4MGNtYzBQMXAwajJMTFpJMXJGdEUKLS0tIDl0bSt3bjErWnhEVEZRU044ZTU4
            MUN0V3lBYXFIbUZwR1o1RG5lRDBVN1UK9iKZBXi1/1nnIrHPHOYaignYFXpx1L8w
            mkRM9TCd5KogRlwghHyqNTBIsPGphotFyYgMVKEWS69pH8Dp5tqu2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hw8r4fnhy55rmvkkrm6lunh5wpmgl6dlam6mhcaxwtm0udvy9u3q78jxgq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T21:16:48Z"
    mac: ENC[AES256_GCM,data:lPUXiXP0OdjYhLiDePkDCWbzMt0Q1tDhJZPZvFNMYHD9/qeyHBRckDp4d2PUs+WdVQ4L6O+UWvsPj+LS1jnycIncOkSHHbjEpfmU+IJ0LjJyHDM0XvFEC1czJo+3N1R/xLigfVSiAgzO4LKzxsgAuJI1mboan1CIDb+w78Abgb0=,iv:P1LX0eoRA9m5aZ2bsHh4TIWyM95GN3UP4K4ebtJ1Fdc=,tag:pnyKvhOa2KzXySSPnqw8pw==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
