---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hajimari
  namespace: home
spec:
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  interval: 15m
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    env:
      TZ: ${TIMEZONE}
    hajimari:
      title: Dashboard
      darkTheme: espresso
      alwaysTargetBlank: true
      showGreeting: true
      showAppGroups: true
      showAppStatus: true
      showBookmarkGroups: false
      showGlobalBookmarks: false
      showAppUrls: false
      defaultEnable: true
      namespaceSelector:
        any: true
      customApps:
      - group: External
        apps:
          - name: DS412
            url: 'https://ds412.josefssonit.se:5001'
            icon: 'nas'
          - name: UniFi
            url: 'https://unifi.josefssonit.se'
            icon: wall-fire
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: hajimari.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
