apiVersion: v1
kind: Secret
metadata:
  name: snmp-exporter-auth
stringData:
  #ENC[AES256_GCM,data:ff60iAInD8mWsp27uRRTvJlWSA4bz5FX7KKu+8JV+zkdMZkVQdLb6/XTVgRZIhHjLgQOgXci4ITOSuaZKG7gl7fKyw4G2GvLcZzjctvgiHgO,iv:2ks8YF9Qfb30uSb4IQKeT8uNMcoViUZbJ4qBmyMopyk=,tag:GHq0429a1mQP02qQnTavUA==,type:comment]
  #ENC[AES256_GCM,data:hjQDPBWi2i4qv1Vuq/MXKTsg7PmjYYLyUbQ4XGwOKWnFpI7mxHvjpcwJ4A7yfZWqc+4sURMrFiGLbAx7n2f1IbroXVow94y2e29+i7gQ0gca,iv:vAng48dMRFblO4ptrv96ZuHruTDwgFXZLCuXrAEB2Xc=,tag:wmC4eRTfkL8pXPZ7K2odyA==,type:comment]
  #ENC[AES256_GCM,data:btHyOMLRC02ffEcX6+3nxXxyoxkaCrF3wvzkzsaCJrtfEVmuqhOdFW4vJZno7My8MR2w0qYnxRAqFiAA/UZl0qHmmVrw,iv:dPMx8YPvt1TN93AfXU7qmABZKODcVaB7dODzOwjzqRc=,tag:GQ2jAatlQtotWmagkbAV4A==,type:comment]
  #
  #ENC[AES256_GCM,data:iuVNVWF83NJXvmcKk9AtHf/BfB97Zo5toASi3VDvSHjHKKdEh7JEqaCj/RwSH72LKco7NWq5EyU5ESj8nPqtbkz9Fx7N,iv:y5UC7mT/OCvkZOM9dZN3NSixXC/GLNQ7BFcf2Ol4+y4=,tag:7q68lmi0wJP9tAyd8SyVdQ==,type:comment]
  #ENC[AES256_GCM,data:Gfj1URmHpPnU7/fBaBNENUd34KYbig+LDQW0l6GbqxAd+PjLLopBmyZqJglVYpHkhutYcKyUglhW9jJ1lfhyGefkyh6N,iv:Dza6NtdF6x38C8+Y0AGgYqP/yF9R5r8yvjBaEUeBd9E=,tag:q4+9QRp3M2Sm7Wh63nTC3A==,type:comment]
  auth.yml: ENC[AES256_GCM,data:Wn03jKFYn90rGJhHGPbJ0E7xlCBs8qb/ymFz8sNhPtbj9/Ixk8WbA30d/hKH/p+q7oC7dDNMurNLaPj2N18iz+IKF+qRI/2l,iv:u7xGk3p0mbO5WXOzSC9NFKwHAAnKv3396gRU0bnfuQ8=,tag:1geYKl56Y/FenDBB0URv2g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdFJwMWM3bmlOM3crOFIz
        dGpWT2VBTTh2dEhjeTZFY2lqbEhBRXpYYm04CjQ5dVoxOUZ6Z3g2WUJYL0xQN3Fv
        S2lDWEhPWDBRd09QT29pWk10emZuWkkKLS0tIGdDOEZsc3pPb0FOYktjNEpUZVpR
        MldYNEZqbVdJbEE3NG9XNy9yUUYvN1EKB5zyCd7j5gWpCjPGNy5E2XhGNLMyBphu
        +7XGekuQtQ5f6Izw04Nenoj8zls6JpdR1bUSQxeYU45EIqP1jGRw6Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hw8r4fnhy55rmvkkrm6lunh5wpmgl6dlam6mhcaxwtm0udvy9u3q78jxgq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-30T19:05:59Z"
  mac: ENC[AES256_GCM,data:VnS0DMK6pCSnHXcFsvQ5+B/6KKJXnX9IL8E6/i8ck3CQ8xQl4LsOVdaPgTTfpIC0uYxNLPAABIalV+Vy2LdeHAziLAuj2jq3gh5Dl6Pur24e8Bb1STBu89Jx2a16be9zPVGQfq+cYctY0XEsYWRMJkydRtnFHY3rUvT2bAZ453E=,iv:zir6RaDgFpVwCNcpSq2HqRYUXABr+iXSL+I0F7XRmWk=,tag:wLvFKtM91JPwYQMOovZEPw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
