apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:wy675Hf3uey9ywHqDQPpuZ4G77buBjX5TyhjqPpA8+Q=,iv:fiFXHEA1JbZw8zKEiZtot5lS2godcNDhdq7xAUPWsEo=,tag:jZlqiIsCLwkeMUY8EuqnIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1penp3cgk75mq57r3ytlqgxa53vh2gvvwx2w3q688gpxg4p6v4p7q7jkpdn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2QkJ3TnFBMitDaFREOVFF
            VFlORk1NOWFGNXlMd0JwQjlLRm5VdGExeG5FCjQ3MlJ5M2JHWmU3YXlEcUxOVDdk
            MzVOcFFBZWlEMlBCS1kyZk1SSHYvalkKLS0tIDNhbDg0VlV2SnExdHVna0ZrRnow
            c3RUVy9YZFErenpDa2NwdEJyMElzQVEK7i+OKKAAfIhjjCvktQJbjt4fJDUdOFI8
            5dDof7A7h1NpO2h45u7iAi4bCLE4yRmZwfn9GdIomRVb/gosiOeRaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-08T18:19:33Z"
    mac: ENC[AES256_GCM,data:rsgE/ZSolkpkmOf08rDXD8IPOTOW+XVD9JJHLYvSnFyjRVAn2PGd+22EVUrjIVGvUnhTE+3gb8SuM6DM8h5/P09b0+kwxLWS9PGGqwjoCp95Dy7dzOiShcfROtyk5oy7MyIKBHeXT6iWzcH3Bj5TuPQlWQb2RhXLax5OMTVZZ50=,iv:7MFL7etd9il38ZrVJD2jihMvnxakfM4ZUv9P28wHqJI=,tag:w/vQPmM3gC2kSttWV3GyGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
