apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:AmxWiuAFAdmJm2m/0wMEL86o3yDU8LtrUJiOyG3CsMo=,iv:r1AKhkAl8XO41WKeEDwv0iCPzK1QFeGRGE6MWxt/oZQ=,tag:g4S2g+yheWNUckUjsOAxLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1penp3cgk75mq57r3ytlqgxa53vh2gvvwx2w3q688gpxg4p6v4p7q7jkpdn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Z2FYb3NNNnJGbFhYWk5n
            ZVZvbUFrc1lGKyt5elkwRFM1eEQ2MldMbmpnCmt2S2JYWm5RMkMybFMyZ2RXdkRM
            VDBJUGI3R21UbVI4OE5YcEo4NEp6Y1EKLS0tIEVTOXY3M2t3cExLajZKQ1lwbmtD
            OGF4LzdwdnA1NjRxN0V1RnBlY1R0Z2MKbVlHzHpc+gui0/h0JeAsKFR8eEnnHnZQ
            O/KZvsOf/j+Gxhe/TejanGc9bzhU9QLtU7kPg8vLhx+Efeb1iE6OsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-08T18:10:59Z"
    mac: ENC[AES256_GCM,data:IWyAMEdEWJ0VsDxHY8UJHNV4v/P8TNnYnrCnSRnhU60IkXdcg7O1f+vigkJT1s+nNfCcB+AVP+KaU75jdXRoB5+Q9C/4I0N8d5V9K2Ib1zJH9CqJ2H5zacCmHfwj5pbKnYdcjQhLfHyLDgwq4MAkKWV8FCI3bgk3FJ0ftpMttzc=,iv:KVX6hf/Lo8PPqNGX5dB6e7HwGdLGukTL40l7XQv0lDY=,tag:aVjXZGMQQ2PNXQkL2HMJ3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
