---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-redis-authentik
  namespace: flux-system
spec:
  path: ./kubernetes/apps/databases/redis/app/authentik
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: redis-authentik
      namespace: databases
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-redis-authentik-haproxy
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-redis-authentik
  path: ./kubernetes/apps/databases/redis/app/authentik/haproxy
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: redis-authentik-haproxy
      namespace: databases
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-redis-nextcloud
  namespace: flux-system
spec:
  path: ./kubernetes/apps/databases/redis/app/nextcloud
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: redis-nextcloud
      namespace: databases
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-redis-haproxy
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-redis-nextcloud
  path: ./kubernetes/apps/databases/redis/app/nextcloud/haproxy
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: redis-nextcloud-haproxy
      namespace: databases
  interval: 30m
  retryInterval: 1m
  timeout: 3m
