---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-redis
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-rook-ceph-cluster
  path: ./kubernetes/apps/databases/redis/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: redis
      namespace: databases
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-redis-lb
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-redis
  path: ./kubernetes/apps/databases/redis/lb
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: redis-lb
      namespace: databases
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-redis-authentik
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-rook-ceph-cluster
  path: ./kubernetes/apps/databases/redis/app/authentik
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: authentik-redis
      namespace: databases
  interval: 30m
  retryInterval: 1m
  timeout: 3m
