---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud-redis
  namespace: databases
spec:
  interval: 15m
  chart:
    spec:
      chart: redis
      version: 18.1.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      storageClass: ceph-block
    auth:
      enabled: false
      sentinel: false
    sentinel:
      enabled: true
      masterSet: redis-master
      getMasterTimeout: 30
      startupProbe:
        failureThreshold: 15
      resources:
        requests:
          cpu: 15m
          memory: 100Mi
        limits:
          cpu: 100m
          memory: 500Mi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
