---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-branding
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Mi
  storageClassName: ceph-block
