apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:dlIoRPQ/ZX8=,iv:rLYzxA1yb3SA7d4umfw/q+8FmHr0DF4bHwZJDVW94LM=,tag:bs+jUrBXzFuPqfVNZv2+Hg==,type:str]
    password: ENC[AES256_GCM,data:I6Cc1ByjqHe9t2Nc0fbI5SaDC84=,iv:WRhO1BhEI5XTWsgcQqsjSockVHrLC4q4CAuw2L4yFvs=,tag:K261MY/AyK3X80N4mhVA1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y6admte6g24crgupz4lpaszp0vxr9nntyjprjk27trp9ustvzumsml44sg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQmlkSE1oWjFhbEVBdTNU
            UXFMSE1UcFVIRFJQSjBZeXFaKzlxdEYvY0hzCnBXOW0vWWJzQzUrVG4zUDlXVFhC
            NDNOR1RCSi9XZVlaQmVCZGhrbTVlNTgKLS0tIEpmeGFoNUFrYjZNc1J4cFY0ay9F
            bEVmQVNKZ3Q5enl1ZlVFYU84bmZEc00KnRTx+HmaMppnPCxmfsCR9fIRhf81SJwn
            JhKYm+PEP0hvOJODcCx8sih83BnqchIHiVaRck8RFa+d6fs3nKzCoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-18T14:49:32Z"
    mac: ENC[AES256_GCM,data:DYuwcJ4C/8GGJvx+3HFnOIhSFZ3nbPiCSGKpyM7G5H5zP29fGaSI3qd4hh/ONmHddXZwmB7PMVwnfFwB+arMqLdsG7/BEtm0YgjS+7v5agJkT635XYesQt/l1+KFS2ngskgmjWjv3HOQ1YTKIg73HJcjj+0hYi5VddZHt+KBHfE=,iv:By16X/eLZ3IbwJBc+J3pP0sWpPAZIx5UOGpxGKvS4jY=,tag:IJd6IIduXYK60YV21kuCeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
