apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:jotCKixw,iv:bxf9e2rSLhMDB6aJCIkfWx+ixCmDBVBTAkIOP9iilNc=,tag:fNW89wVaw0QASpc4/Sl+Mg==,type:str]
    password: ENC[AES256_GCM,data:cVj0JHZlYivlm2LPWGpP6mzrKcE=,iv:06YVnUX2UWPrKNVGFlKc/RGZrAk8WQhicWlco02ldQM=,tag:5W+wHzZQWgjfPc9M//354A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y6admte6g24crgupz4lpaszp0vxr9nntyjprjk27trp9ustvzumsml44sg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdUk4NStod1FiSVZSeFp0
            RjVyZitmdGRmSjJzZnVFa2gwNUZibml3d3dvCmUvTnZrUWRmREhrTmt1SnQ1R3Fi
            RkEwOU8rQVFRWEtldmtDMjQzYko1NjgKLS0tIGJWenl4RGdyaS9mRDQ1cGVjMGFY
            bHlFY1RUWjZKdFMvek5yOHVBa1lzd28KuTjuFpSUaqP9sRKd3Afogkg0sFQ7X3j3
            ZCa2+2M9lHV0eZ4FxAnzY9P1PO9yX1sU5/hNPuXucNMUY6z+/SJMHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-18T12:47:53Z"
    mac: ENC[AES256_GCM,data:tewUa/2MGyLg1XMjpEao8szs0xhsU2otHYVih7cigWMpiu6kpALjCyfY3K4INhT4oLJ3Hq8kx+jvnutp178WyYg/VSo2pS3255wXxG+VBfvjUa31h6X1a77qHbacAVj39p24KD1i9/78662jCWOWv6WiAMFbSlZMTnznbFup6mo=,iv:7rg+YJjM1PcRYlrUmM34UZOb80b8tUrp/Jpdl17G7zs=,tag:QbQIbMcyJNbswJNYTVd90A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
