---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  namespace: databases
  annotations:
    coredns.io/hostname: "postgres.${SECRET_DOMAIN}"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  externalIPs: ["${SVC_POSTGRES_ADDR}"]
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres-v15
    role: primary
