apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:cAUvkNGTf4gbpJjsheU/DRIjMHrPcX2HjwfbxuJ2sBMzhEgLNssVRg==,iv:IyoWuac18txDbsTK2Hgy7r4avDCgleVTqUxdE+pHGKs=,tag:TekBlfEVNQjoYI0LJZwdaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1penp3cgk75mq57r3ytlqgxa53vh2gvvwx2w3q688gpxg4p6v4p7q7jkpdn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2c2pGZGlnWm00MGhSNXJZ
            ZllIeE5LZm5RcGYyR1NleFVkdExoL25XakZjCkFOcjZ0L0docTcvN3FmT2xRQTlk
            RmxLeWZ1SnpPM3dMczFhalhXNTIvSXMKLS0tIFg4Q2w2WmRjMEI1TWFwN0VmY3py
            YmdDSHd0U21jcS9zZ1kwbWJLSk16OW8Ktt2Q6dsjYYNYSQ7gRnoBuN+YdKHF3zBZ
            Ur4TcJ/5+WivjrzLS9wm5s36CS9IXGYd1oFXQr65dUeILlj1HiWs4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-08T19:48:31Z"
    mac: ENC[AES256_GCM,data:IuX6EM9BHckD97aw0gH+pWX/FQWSnlXMts7AWXpl4jjlyQsurldYZcPFTiX1BMzFYaLH89/g6eDxchcRM1+vX/HcwSI5XW3w6aYz4ekwNvJTaJZZIML7bNjywIwoFW0zHsLHQt+mfpX68XFCC9PtIzKdLdaXL0hPjcQPM7ddrxs=,iv:mf4sCkTLvaY3jKJH9VbfGV+1CDtqJzVhAZgfS19rqZY=,tag:/ZWEPWU2hmcsJYF8dctNSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
