apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:w1ShwlR4sgg83mjtMiyheISuxsajiYMof65IBhfsHPsDLyWedcVOng==,iv:m+EP79S3T2LFSdMtWtRH+mffXjVqlVgwiuPL0Zk892c=,tag:2mFgrPbeiXv3jsrbDcFMRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1penp3cgk75mq57r3ytlqgxa53vh2gvvwx2w3q688gpxg4p6v4p7q7jkpdn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNi9UM1dyMW81TGxuNkhn
            akdDNUlFM3krdnFOcURwT0dnVXAzQVdETlZjCkdCeVRwV0tiU1Y1dUZZUXBYTUFK
            dkg3dmdxVlRMVDczTzBkVGUyMFpIc2MKLS0tIFo5YjhVaFFWRHN3VW9wZUVSeCtm
            d0hCNFBCSUhNVFNZUjJsTDdjcnNZS2cKqdBZr/R8fJBFhdgn8PyBnAchCEAdDH9T
            Tg60zxCHHUpYQdcB7DrUQrpOPijxmLtCty22KZ73yJVzq9Dr+bn9XQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-08T21:25:59Z"
    mac: ENC[AES256_GCM,data:/4Y0rF4ocsAvSN8VmH7GHnlggQXTEfC/afWNIOwgzX+LMENLJQpciZkk6yvEcFGUgDtwwDW3bUavWaBEe9Fu25wz4FJyAXlXDdoXkno0IWW+i1trnKOWjfXskCCHcany0zhG4bsJn9WN+ZVBfVDQMzKYmuAbnc1HrOxYOr4oqXU=,iv:DEewVdsJfZ2O5NnEpyOMA2njLaUkXkJoL4STCEK06/A=,tag:+RJ0X2HI9zouKv9TEIZsBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
