apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    labels:
        cnpg.io/reload: "true"
stringData:
    username: ENC[AES256_GCM,data:Fbgyx6r8sWg=,iv:VmxKxV7Sl46VrrjcApMVe0s90HHPKqRUEE7Su4z8xLk=,tag:+uHANP0S8HHVm1L6Be2UAw==,type:str]
    password: ENC[AES256_GCM,data:1w9tTae2esvAdEtZjQ3fotjNb7dgnaEkZkdpg5sSCZ7Y4iXl9F1RIDSyb3IF/TdsOV9UHsFpBRWADN8HSb0Caw==,iv:MiUvQXlA9MP+EI2XeTnQxrv5ssLfbXY4btlSpUOCY2k=,tag:325w7OZGzWslKHiDLj/OZA==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:T/zoBG5VfZsLimd7ng6u/u6ZYZs=,iv:0a46IJYqUDHa5meMOJqdXcpsoyDyg4M0WlNftBVwiOs=,tag:lFGN+khOrRLEraLnU5gFcg==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:BmkrIMjL2YQ9qPdouUqxfuXmFvIVNRGBvsIlOuHsDqVkg+viO91YDQ==,iv:I/ybtGAbpc8lI7nS8Z13fHTBjVWHle81XULNuRZ0BrU=,tag:ePkTT9fZWW7uaoTOp7XHgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUTg1RlRyS2tDS1pxWGJt
            R1lGS2IvZ3BjUWcyaFJ5Q2hxVWZNODIwK1RjCmhYTlI5NnRaSU1NWVZocmt1K21Y
            MktwajlPNEdmNkN1VlBScHBhZURGSTAKLS0tIDNTVE9Wd0JuTXc3dGhuU0kxTFRR
            dUhEUWFaM2QxREQvSHNZS21DSHFhQlkKU5i2yGdVOpMEQdPMKc+/WM9A5yacUQ7j
            C4PeWOKxtsZdNhXvvXUyOAjl0LbaMa0n+xGZhDTCkflk/2yA4dShuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hw8r4fnhy55rmvkkrm6lunh5wpmgl6dlam6mhcaxwtm0udvy9u3q78jxgq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T16:28:47Z"
    mac: ENC[AES256_GCM,data:234mR041E9rkTKGuPpHH0gUpA5LRDcsRIJlYDK8kjVAkWzjdnU6bmAya9b8/a27O5yDXGxf//Hc1yryt58MLAy5dfVCbI3brQRJUUhm/O6pzD8W2C5lWcY3UzshX5RheCPV/HD+2p1q51ifsMOucpm7CNwh7bdyY/uZewXWPW9I=,iv:9hKSkzRbhPK+O7fj3Z99QJmkmbQxjsAZDhdZpwQfopQ=,tag:cimHBR1Iio4gG96Ni0e2kQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
