apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
    namespace: security
stringData:
    #ENC[AES256_GCM,data:qrZO41LHtE/guSmjjow=,iv:G6Vpo7cfevlD4qsRJI78HiAC8Ac/LnUHNpF/GouytnA=,tag:ZyZU9MbgXqvIjSt/CnnC3Q==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:LNchExA=,iv:SQa0Gy7nJDL/GFH0X1AzAj7V8Ljuc0M1yB3K1+uUMaM=,tag:Z9pjwySkIl9nghX3KOU8sg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:07oWZNND48XCL+NAHfUezcnL9gZRifAjaeCCTeAJYWv5NuAIZ9Gg6SGH1A==,iv:zf9IKAYCkJKpKlwdd/KPzueqYjTbVVp61sDuL1rX8yk=,tag:vzpU5wv9/T59pI3iqdM/UQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:sdfPGm2wjo+F,iv:Iw8vj7TezeidNbOeK++ePS2fNV2O1Nvm1ZL89V32hUk=,tag:Thb3l2pFZtRA/RkMw4mDxg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:QHdgcUTRHPLarsJ6zO5bCEKKvWo=,iv:G2pbfeaKaixhZT4Bn02/eQZ/20OcJj3sutpSCa3mI1g=,tag:RgmdK1i6//jO33naWT1TSg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:nIkLGxM4ifjxZiuYnstaP9jDhFhinTvCwawUZ8+9f6QYcjH0F8HEPjCjepkBFS5iXrScKMNirK9c3SPj5wH/iA==,iv:KA8vhLEXO3QnVkvo7gCRAgQp3vLF37fXGWrEQNLk8Mk=,tag:7zWicPGINw0W4/Q9/bSNtQ==,type:str]
    #ENC[AES256_GCM,data:XTdRl/Ck,iv:DUHSTfxw07V3L5kYm8JHu69h9CFIFUphe8hUCt7Frr0=,tag:TuFAavuBUYyj1su9KvmLhQ==,type:comment]
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:QqvbpYhTpbhLRS07u3XVqYs4qOyGPakKzRRS9XVVQ0w=,iv:f7w9NazNQggMiNQQQP44n6NzI3FvsuQJjcL4tY9ieMw=,tag:9oUqNiKIbGdo21JYYg6CnQ==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:azht4iT2GbHVI63/4R+1tRvyrjc=,iv:eVvrSXvWV1206QshoeZYBqGikarvMaid4vwOVVSt8H0=,tag:fJdTIFQWAdD+3ageIQIIzg==,type:str]
    LLDAP_USER_DN: ENC[AES256_GCM,data:1NNVVvNPX+Gh4w==,iv:wq3F76xXJ8ZKSh36/reqVYjKhBQrwN0KpSOYtqZhiBM=,tag:uV/JR1V2s7vIng2/6TYJUQ==,type:str]
    LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:AeFktd9Wts4ZB0RASV4tG5Y=,iv:wQrfOiQ91j8cPgzdsy2QpgU4/7bp6Y7YJtrJU0bTY+I=,tag:xUBGAck2AQQqprT+XqcUCQ==,type:str]
    LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:0IdRHjotKclbMiLts7Cy0Fn1qzQ=,iv:ciw9Oy3qn8ZuCc7gfrvelZO+bon8V3kI3qV7TnAn3F4=,tag:W9yxZ7PAfusys/kSuUwxSw==,type:str]
    LLDAP_DATABASE_URL: ENC[AES256_GCM,data:0xVYFD5hu3FGFV26uff0mMSALdBOIhwpwnUQfWqQPYploCHmceraQKkDLXXbH1d91DcF8id0vSfVygjTlBukP5Rf5neg8FxGpZ5BnnzotQeMzH8sOLkTj1PaNA==,iv:8oMhSs8e6055Quo2gDpuPqhnIfcyruNXBl7fFhQRmBM=,tag:1w5AFTcsL8QGvJ0j7UBS7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y6admte6g24crgupz4lpaszp0vxr9nntyjprjk27trp9ustvzumsml44sg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWEptNXovcG1UOExRTzBG
            NlBSdmFWZTRtT2JFbU80MnN0WFBqNnVoL204CkdLdnFuRUR2aHUreFRxTEpxUU1z
            VFF1TjBURzBPWFRzSGZzV3p6YWZ0NDAKLS0tIHhUZWdvL1NoMk5vTWNTaUoreDda
            eTRYOXdLeVFSd1hZNDlRc3NwdHpoY1kKeVsEeNv7d97vTrWsDsD2HrVXokYpssqV
            W60khKgQXI1pup1w74zLh94LClxnnsRe2Tm9jq50Fzh0/k3Rx6b2aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-12T09:28:04Z"
    mac: ENC[AES256_GCM,data:rYgIGOyyc4DW+CZAKU4hW9R0VtvklVVr2Idgfc5ZCqwAV6EhZ8esg1IGP6lwm8jFHznpEZdKd3P8OCDDgTwkdFTxc4CNp2qXueqIKya+Y790qgESwGcevovKrdt86ZZUJcZz9VLGuWm2MCeG7mRFxcL11nw9u3UBIOUAuzUuXGg=,iv:BpTCH0L7fbFzRgpezqzoos1Y1Tl2XZ9LCN78kJNrzps=,tag:2KoTqa/Ttui9v1bT/Gkh3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
