---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: goldilocks
      version: 7.0.1
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      resources:
        requests:
          cpu: 33m
          memory: 64M
        limits:
          cpu: 876m
          memory: 1242M
    dashboard:
      replicaCount: 1
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: mdi:align-vertical-top
          hajimari.io/appName: "Goldilocks"
          hajimari.io/group: "monitoring"
        hosts:
          - host: &host "goldilocks.${SECRET_DOMAIN}"
            paths:
              - path: /
                type: Prefix
        tls:
          - hosts:
              - *host
      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          cpu: 275m
          memory: 908M
