---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud-redis-haproxy
  namespace: databases
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicas: 3
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: public.ecr.aws/docker/library/haproxy
      tag: 2.8.4-alpine
    service:
      main:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${SVC_NEXTCLOUD_REDIS_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8080
            targetPort: 8080
          redis-read:
            port: 6380
            targetPort: 6380
          redis-write:
            port: 6379
            targetPort: 6379
          redis-sentinel:
            port: 26379
            targetPort: 26379
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/appName: "Nextcloud-Redis Load Balancer"
          hajimari.io/icon: simple-icons:redis
        hosts:
          - host: "redis-nextcloud.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    podSecurityContext:
      runAsUser: 99
      runAsGroup: 99
      fsGroup: 99
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        type: configMap
        name: redis-nextcloud-haproxy-configmap
        mountPath: /usr/local/etc/haproxy/haproxy.cfg
        subPath: haproxy.cfg
        readOnly: true
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
